// <auto-generated />
using DropShot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DropShot.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260327000000_AddPlayerTable")]
    partial class AddPlayerTable
    {
    }
}
