// <auto-generated />
using System;
using DropShot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DropShot.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260326000000_AddSavedMatchMetadata")]
    partial class AddSavedMatchMetadata
    {
    }
}
