// <auto-generated />
using DropShot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DropShot.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260709000000_RemoveReminderBoolColumns")]
    partial class RemoveReminderBoolColumns
    {
    }
}
