// <auto-generated />
using System;
using DropShot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DropShot.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260422142936_ReplaceLeaguesWithCompetitionDivisions")]
    partial class ReplaceLeaguesWithCompetitionDivisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DropShot.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaypalPayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaypalSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DropShot.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("DropShot.Models.ClubAdministrator", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubAdministrators");
                });

            modelBuilder.Entity("DropShot.Models.ClubEmailTemplate", b =>
                {
                    b.Property<int>("ClubEmailTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubEmailTemplateId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClubEmailTemplateId");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubEmailTemplates");
                });

            modelBuilder.Entity("DropShot.Models.ClubLadder", b =>
                {
                    b.Property<int>("ClubLadderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubLadderId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("InactivityDeductionDays")
                        .HasColumnType("int");

                    b.Property<int>("InactivityDeductionPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("KFactor")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RulesSetId")
                        .HasColumnType("int");

                    b.HasKey("ClubLadderId");

                    b.HasIndex("ClubId");

                    b.HasIndex("RulesSetId");

                    b.ToTable("ClubLadders");
                });

            modelBuilder.Entity("DropShot.Models.ClubLinkRequest", b =>
                {
                    b.Property<int>("ClubLinkRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubLinkRequestId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClubLinkRequestId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("ClubId", "Status");

                    b.HasIndex("UserId", "ClubId")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.ToTable("ClubLinkRequests");
                });

            modelBuilder.Entity("DropShot.Models.ClubPlayer", b =>
                {
                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClubId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ClubMembers", (string)null);
                });

            modelBuilder.Entity("DropShot.Models.ClubSchedulingTemplate", b =>
                {
                    b.Property<int>("ClubSchedulingTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubSchedulingTemplateId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClubSchedulingTemplateId");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubSchedulingTemplates");
                });

            modelBuilder.Entity("DropShot.Models.ClubSchedulingTemplateWindow", b =>
                {
                    b.Property<int>("ClubSchedulingTemplateWindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubSchedulingTemplateWindowId"));

                    b.Property<int>("ClubSchedulingTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ClubSchedulingTemplateWindowId");

                    b.HasIndex("ClubSchedulingTemplateId");

                    b.ToTable("ClubSchedulingTemplateWindows");
                });

            modelBuilder.Entity("DropShot.Models.Competition", b =>
                {
                    b.Property<int>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionID"));

                    b.Property<int>("BestOf")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionFormat")
                        .HasColumnType("int");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte?>("EligibleSex")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("GamesPerSet")
                        .HasColumnType("int");

                    b.Property<bool>("HasDivisions")
                        .HasColumnType("bit");

                    b.Property<int?>("HostClubId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<byte>("LeagueScoring")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MatchFormat")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisterByDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequireVerification")
                        .HasColumnType("bit");

                    b.Property<string>("RubberTemplateKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("RulesSetId")
                        .HasColumnType("int");

                    b.Property<int?>("SeededFromCompetitionId")
                        .HasColumnType("int");

                    b.Property<byte>("SetWinMode")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("CompetitionID");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("HostClubId");

                    b.HasIndex("RulesSetId");

                    b.HasIndex("SeededFromCompetitionId");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionAdmin", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompetitionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CompetitionAdmins");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionAllowedPlayer", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompetitionId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CompetitionAllowedPlayers");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionDivision", b =>
                {
                    b.Property<int>("CompetitionDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionDivisionId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.HasKey("CompetitionDivisionId");

                    b.HasIndex("CompetitionId", "Rank")
                        .IsUnique();

                    b.ToTable("CompetitionDivisions");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionFixture", b =>
                {
                    b.Property<int>("CompetitionFixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionFixtureId"));

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int?>("CompetitionStageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<int?>("CourtPairId")
                        .HasColumnType("int");

                    b.Property<string>("FixtureLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalResultSummary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OriginalWinnerPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player4Id")
                        .HasColumnType("int");

                    b.Property<bool>("ResultModifiedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SavedMatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("VerificationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionFixtureId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitionStageId");

                    b.HasIndex("CourtId");

                    b.HasIndex("CourtPairId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("Player3Id");

                    b.HasIndex("Player4Id");

                    b.HasIndex("SavedMatchId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("CompetitionFixtures");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionMatchWindow", b =>
                {
                    b.Property<int>("CompetitionMatchWindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionMatchWindowId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("CompetitionMatchWindowId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CourtId");

                    b.ToTable("CompetitionMatchWindows");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionParticipant", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("CompetitionDivisionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionId", "PlayerId");

                    b.HasIndex("CompetitionDivisionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("CompetitionParticipants");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionRubberTemplate", b =>
                {
                    b.Property<int>("CompetitionRubberTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionRubberTemplateId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionRubberTemplateId");

                    b.HasIndex("CompetitionId")
                        .IsUnique();

                    b.ToTable("CompetitionRubberTemplates");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionStage", b =>
                {
                    b.Property<int>("CompetitionStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionStageId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<byte>("StageType")
                        .HasColumnType("tinyint");

                    b.HasKey("CompetitionStageId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionStages");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTeam", b =>
                {
                    b.Property<int>("CompetitionTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionTeamId"));

                    b.Property<int?>("CaptainPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("CompetitionDivisionId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompetitionTeamId");

                    b.HasIndex("CaptainPlayerId");

                    b.HasIndex("CompetitionDivisionId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionTeams");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTemplate", b =>
                {
                    b.Property<int>("CompetitionTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionTemplateId"));

                    b.Property<int?>("BestOf")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<byte?>("EligibleSex")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Format")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RulesSetId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionTemplateId");

                    b.HasIndex("ClubId");

                    b.ToTable("CompetitionTemplates");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTemplateWindow", b =>
                {
                    b.Property<int>("CompetitionTemplateWindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionTemplateWindowId"));

                    b.Property<int>("CompetitionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("CompetitionTemplateWindowId");

                    b.HasIndex("CompetitionTemplateId");

                    b.ToTable("CompetitionTemplateWindows");
                });

            modelBuilder.Entity("DropShot.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Surface")
                        .HasColumnType("tinyint");

                    b.HasKey("CourtId");

                    b.HasIndex("ClubId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("DropShot.Models.CourtPair", b =>
                {
                    b.Property<int>("CourtPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtPairId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("Court1Id")
                        .HasColumnType("int");

                    b.Property<int>("Court2Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourtPairId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("Court1Id");

                    b.HasIndex("Court2Id");

                    b.ToTable("CourtPairs");
                });

            modelBuilder.Entity("DropShot.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HostClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("HostClubId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DropShot.Models.LadderEntry", b =>
                {
                    b.Property<int>("LadderEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LadderEntryId"));

                    b.Property<int>("ClubLadderId")
                        .HasColumnType("int");

                    b.Property<double>("EloRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMatchAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("LadderEntryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ClubLadderId", "PlayerId")
                        .IsUnique();

                    b.ToTable("LadderEntries");
                });

            modelBuilder.Entity("DropShot.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("ContactPreferences")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByClubId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool?>("DefaultGameScoring")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayerId");

                    b.HasIndex("CreatedByClubId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DropShot.Models.PlayerFriend", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("FriendPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "FriendPlayerId");

                    b.HasIndex("FriendPlayerId");

                    b.ToTable("PlayerFriends");
                });

            modelBuilder.Entity("DropShot.Models.PlayerInvitation", b =>
                {
                    b.Property<int>("PlayerInvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerInvitationId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcceptedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LightPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SentToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerInvitationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LightPlayerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PlayerInvitations");
                });

            modelBuilder.Entity("DropShot.Models.RoleSwitchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("RoleSwitchLogs");
                });

            modelBuilder.Entity("DropShot.Models.Rubber", b =>
                {
                    b.Property<int>("RubberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubberId"));

                    b.Property<int?>("AwayGames")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGamesTotal")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPlayer1Id")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPlayer2Id")
                        .HasColumnType("int");

                    b.Property<string>("AwayRolesJson")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("AwaySetsWon")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionFixtureId")
                        .HasColumnType("int");

                    b.Property<int>("CourtNumber")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGames")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGamesTotal")
                        .HasColumnType("int");

                    b.Property<int?>("HomePlayer1Id")
                        .HasColumnType("int");

                    b.Property<int?>("HomePlayer2Id")
                        .HasColumnType("int");

                    b.Property<string>("HomeRolesJson")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("HomeSetsWon")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("SavedMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("int");

                    b.HasKey("RubberId");

                    b.HasIndex("AwayPlayer1Id");

                    b.HasIndex("AwayPlayer2Id");

                    b.HasIndex("CompetitionFixtureId");

                    b.HasIndex("HomePlayer1Id");

                    b.HasIndex("HomePlayer2Id");

                    b.HasIndex("SavedMatchId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("Rubbers", (string)null);
                });

            modelBuilder.Entity("DropShot.Models.RubberTemplateRubber", b =>
                {
                    b.Property<int>("RubberTemplateRubberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubberTemplateRubberId"));

                    b.Property<string>("AwayRolesJson")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CompetitionRubberTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("CourtNumber")
                        .HasColumnType("int");

                    b.Property<string>("HomeRolesJson")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RubberTemplateRubberId");

                    b.HasIndex("CompetitionRubberTemplateId");

                    b.ToTable("RubberTemplateRubbers");
                });

            modelBuilder.Entity("DropShot.Models.RulesSet", b =>
                {
                    b.Property<int>("RulesSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RulesSetId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RulesSetId");

                    b.HasIndex("ClubId");

                    b.ToTable("RulesSets");
                });

            modelBuilder.Entity("DropShot.Models.RulesSetItem", b =>
                {
                    b.Property<int>("RulesSetItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RulesSetItemId"));

                    b.Property<string>("RuleText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RulesSetId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RulesSetItemId");

                    b.HasIndex("RulesSetId");

                    b.ToTable("RulesSetItems");
                });

            modelBuilder.Entity("DropShot.Models.SavedMatch", b =>
                {
                    b.Property<int>("SavedMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedMatchId"));

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("int");

                    b.Property<string>("Player2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<string>("Player3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player3Id")
                        .HasColumnType("int");

                    b.Property<string>("Player4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player4Id")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("int");

                    b.HasKey("SavedMatchId");

                    b.HasIndex("CourtId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("Player3Id");

                    b.HasIndex("Player4Id");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("SavedMatch");
                });

            modelBuilder.Entity("DropShot.Models.Score", b =>
                {
                    b.Property<int>("ScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreID"));

                    b.Property<int>("Player1")
                        .HasColumnType("int");

                    b.Property<int>("Player2")
                        .HasColumnType("int");

                    b.HasKey("ScoreID");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("DropShot.Models.ScoreboardDisplaySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<bool>("Fullscreen")
                        .HasColumnType("bit");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("default");

                    b.Property<string>("LiveStreamUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ShowLiveStream")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourtId")
                        .IsUnique();

                    b.ToTable("ScoreboardDisplaySettings");
                });

            modelBuilder.Entity("DropShot.Models.UserPlayer", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("UserPlayers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DropShot.Models.ClubAdministrator", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("Administrators")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropShot.Models.ClubEmailTemplate", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DropShot.Models.ClubLadder", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("Ladders")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.RulesSet", "Rules")
                        .WithMany("Ladders")
                        .HasForeignKey("RulesSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("DropShot.Models.ClubLinkRequest", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Data.ApplicationUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropShot.Models.ClubPlayer", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany("ClubMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DropShot.Models.ClubSchedulingTemplate", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("SchedulingTemplates")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DropShot.Models.ClubSchedulingTemplateWindow", b =>
                {
                    b.HasOne("DropShot.Models.ClubSchedulingTemplate", "Template")
                        .WithMany("Windows")
                        .HasForeignKey("ClubSchedulingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DropShot.Models.Competition", b =>
                {
                    b.HasOne("DropShot.Data.ApplicationUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Event", "Event")
                        .WithMany("Competitions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.Club", "HostClub")
                        .WithMany("Competitions")
                        .HasForeignKey("HostClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.RulesSet", "Rules")
                        .WithMany("Competitions")
                        .HasForeignKey("RulesSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.Competition", "SeededFromCompetition")
                        .WithMany()
                        .HasForeignKey("SeededFromCompetitionId");

                    b.Navigation("CreatorUser");

                    b.Navigation("Event");

                    b.Navigation("HostClub");

                    b.Navigation("Rules");

                    b.Navigation("SeededFromCompetition");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionAdmin", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Admins")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionAllowedPlayer", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("AllowedPlayers")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionDivision", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Divisions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionFixture", b =>
                {
                    b.HasOne("DropShot.Models.CompetitionTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Fixtures")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.CompetitionStage", "Stage")
                        .WithMany("Fixtures")
                        .HasForeignKey("CompetitionStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Court", "Court")
                        .WithMany("Fixtures")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.CourtPair", "CourtPair")
                        .WithMany()
                        .HasForeignKey("CourtPairId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DropShot.Models.CompetitionTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DropShot.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", "Player3")
                        .WithMany()
                        .HasForeignKey("Player3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", "Player4")
                        .WithMany()
                        .HasForeignKey("Player4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.SavedMatch", "SavedMatch")
                        .WithMany()
                        .HasForeignKey("SavedMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.CompetitionTeam", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("Court");

                    b.Navigation("CourtPair");

                    b.Navigation("HomeTeam");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Player3");

                    b.Navigation("Player4");

                    b.Navigation("SavedMatch");

                    b.Navigation("Stage");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionMatchWindow", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("MatchWindows")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competition");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionParticipant", b =>
                {
                    b.HasOne("DropShot.Models.CompetitionDivision", "Division")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionDivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany("CompetitionParticipants")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.CompetitionTeam", "Team")
                        .WithMany("Participants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Competition");

                    b.Navigation("Division");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionRubberTemplate", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithOne("RubberTemplate")
                        .HasForeignKey("DropShot.Models.CompetitionRubberTemplate", "CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionStage", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Stages")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTeam", b =>
                {
                    b.HasOne("DropShot.Models.Player", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.CompetitionDivision", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionDivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Competition");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTemplate", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("CompetitionTemplates")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTemplateWindow", b =>
                {
                    b.HasOne("DropShot.Models.CompetitionTemplate", "Template")
                        .WithMany("Windows")
                        .HasForeignKey("CompetitionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DropShot.Models.Court", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DropShot.Models.CourtPair", b =>
                {
                    b.HasOne("DropShot.Models.Competition", "Competition")
                        .WithMany("CourtPairs")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Court", "Court1")
                        .WithMany()
                        .HasForeignKey("Court1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Court", "Court2")
                        .WithMany()
                        .HasForeignKey("Court2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Court1");

                    b.Navigation("Court2");
                });

            modelBuilder.Entity("DropShot.Models.Event", b =>
                {
                    b.HasOne("DropShot.Models.Club", "HostClub")
                        .WithMany("Events")
                        .HasForeignKey("HostClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HostClub");
                });

            modelBuilder.Entity("DropShot.Models.LadderEntry", b =>
                {
                    b.HasOne("DropShot.Models.ClubLadder", "Ladder")
                        .WithMany("Entries")
                        .HasForeignKey("ClubLadderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ladder");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DropShot.Models.Player", b =>
                {
                    b.HasOne("DropShot.Models.Club", "CreatedByClub")
                        .WithMany()
                        .HasForeignKey("CreatedByClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByClub");

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DropShot.Models.PlayerFriend", b =>
                {
                    b.HasOne("DropShot.Models.Player", "Friend")
                        .WithMany("FriendOf")
                        .HasForeignKey("FriendPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany("Friends")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DropShot.Models.PlayerInvitation", b =>
                {
                    b.HasOne("DropShot.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "LightPlayer")
                        .WithMany()
                        .HasForeignKey("LightPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("LightPlayer");
                });

            modelBuilder.Entity("DropShot.Models.Rubber", b =>
                {
                    b.HasOne("DropShot.Models.Player", "AwayPlayer1")
                        .WithMany()
                        .HasForeignKey("AwayPlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", "AwayPlayer2")
                        .WithMany()
                        .HasForeignKey("AwayPlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.CompetitionFixture", "Fixture")
                        .WithMany("Rubbers")
                        .HasForeignKey("CompetitionFixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Models.Player", "HomePlayer1")
                        .WithMany()
                        .HasForeignKey("HomePlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", "HomePlayer2")
                        .WithMany()
                        .HasForeignKey("HomePlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.SavedMatch", "SavedMatch")
                        .WithMany()
                        .HasForeignKey("SavedMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.CompetitionTeam", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AwayPlayer1");

                    b.Navigation("AwayPlayer2");

                    b.Navigation("Fixture");

                    b.Navigation("HomePlayer1");

                    b.Navigation("HomePlayer2");

                    b.Navigation("SavedMatch");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("DropShot.Models.RubberTemplateRubber", b =>
                {
                    b.HasOne("DropShot.Models.CompetitionRubberTemplate", "Template")
                        .WithMany("Rubbers")
                        .HasForeignKey("CompetitionRubberTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DropShot.Models.RulesSet", b =>
                {
                    b.HasOne("DropShot.Models.Club", "Club")
                        .WithMany("RulesSets")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DropShot.Models.RulesSetItem", b =>
                {
                    b.HasOne("DropShot.Models.RulesSet", "RulesSet")
                        .WithMany("Items")
                        .HasForeignKey("RulesSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RulesSet");
                });

            modelBuilder.Entity("DropShot.Models.SavedMatch", b =>
                {
                    b.HasOne("DropShot.Models.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DropShot.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("Player3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("Player4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DropShot.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DropShot.Models.ScoreboardDisplaySetting", b =>
                {
                    b.HasOne("DropShot.Models.Court", "Court")
                        .WithOne()
                        .HasForeignKey("DropShot.Models.ScoreboardDisplaySetting", "CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("DropShot.Models.UserPlayer", b =>
                {
                    b.HasOne("DropShot.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DropShot.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DropShot.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DropShot.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DropShot.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DropShot.Models.Club", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("CompetitionTemplates");

                    b.Navigation("Competitions");

                    b.Navigation("Courts");

                    b.Navigation("EmailTemplates");

                    b.Navigation("Events");

                    b.Navigation("Ladders");

                    b.Navigation("Players");

                    b.Navigation("RulesSets");

                    b.Navigation("SchedulingTemplates");
                });

            modelBuilder.Entity("DropShot.Models.ClubLadder", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DropShot.Models.ClubSchedulingTemplate", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("DropShot.Models.Competition", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("AllowedPlayers");

                    b.Navigation("CourtPairs");

                    b.Navigation("Divisions");

                    b.Navigation("Fixtures");

                    b.Navigation("MatchWindows");

                    b.Navigation("Participants");

                    b.Navigation("RubberTemplate");

                    b.Navigation("Stages");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionDivision", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionFixture", b =>
                {
                    b.Navigation("Rubbers");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionRubberTemplate", b =>
                {
                    b.Navigation("Rubbers");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionStage", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTeam", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DropShot.Models.CompetitionTemplate", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("DropShot.Models.Court", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("DropShot.Models.Event", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("DropShot.Models.Player", b =>
                {
                    b.Navigation("ClubMemberships");

                    b.Navigation("CompetitionParticipants");

                    b.Navigation("FriendOf");

                    b.Navigation("Friends");
                });

            modelBuilder.Entity("DropShot.Models.RulesSet", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Items");

                    b.Navigation("Ladders");
                });
#pragma warning restore 612, 618
        }
    }
}
