-- Part 5: Hertfordshire, Essex, Berkshire, Buckinghamshire, Oxfordshire, Scotland, Wales

-- =============================================
-- HERTFORDSHIRE
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Berkhamsted LT&SRC', 'Broadwater, Lower Kings Road', NULL, 'Berkhamsted', 'HP4 2AL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gosling LTC', 'Stanborough Road', NULL, 'Welwyn Garden City', 'AL8 6XE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Radlett LT & Squash Club', '425 Watling Street', NULL, 'Radlett', 'WD7 7JG');
INSERT INTO Clubs (Name, Town) VALUES ('Ace Tennis Club', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ashwell TC', 'Ashwell');
INSERT INTO Clubs (Name, Town) VALUES ('Aston LTC', 'Aston');
INSERT INTO Clubs (Name, Town) VALUES ('Barley TC', 'Barley');
INSERT INTO Clubs (Name, Town) VALUES ('Batchwood G&TC', 'St Albans');
INSERT INTO Clubs (Name, Town) VALUES ('Bishops Stortford LTC', 'Bishops Stortford');
INSERT INTO Clubs (Name, Town) VALUES ('Bovingdon & Flaunden TC', 'Bovingdon');
INSERT INTO Clubs (Name, Town) VALUES ('Braughing TC', 'Braughing');
INSERT INTO Clubs (Name, Town) VALUES ('Brookmans Park TC', 'Brookmans Park');
INSERT INTO Clubs (Name, Town) VALUES ('Broxbourne LTC', 'Broxbourne');
INSERT INTO Clubs (Name, Town) VALUES ('Cassiobury TC', 'Watford');
INSERT INTO Clubs (Name, Town) VALUES ('Chipperfield TC', 'Chipperfield');
INSERT INTO Clubs (Name, Town) VALUES ('Chorleywood TC', 'Chorleywood');
INSERT INTO Clubs (Name, Town) VALUES ('Codicote LTC', 'Codicote');
INSERT INTO Clubs (Name, Town) VALUES ('Croxley Tennis Club', 'Croxley Green');
INSERT INTO Clubs (Name, Town) VALUES ('Datchworth TC', 'Datchworth');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Bushey', 'Bushey');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Hatfield', 'Hatfield');
INSERT INTO Clubs (Name, Town) VALUES ('Dellcott Family TC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Digswell Tennis Club', 'Digswell');
INSERT INTO Clubs (Name, Town) VALUES ('Elliswick LTC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Elstree LTC', 'Elstree');
INSERT INTO Clubs (Name, Town) VALUES ('Get Set 4 Tennis Abbots Langley', 'Abbots Langley');
INSERT INTO Clubs (Name, Town) VALUES ('Get Set 4 Tennis Maple Cross', 'Maple Cross');
INSERT INTO Clubs (Name, Town) VALUES ('Greenwood Park LTC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Grosvenor LTC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Harpenden LTC', 'Harpenden');
INSERT INTO Clubs (Name, Town) VALUES ('Hertford LTC', 'Hertford');
INSERT INTO Clubs (Name, Town) VALUES ('Hitchin TC', 'Hitchin');
INSERT INTO Clubs (Name, Town) VALUES ('Hoddesdon LTC', 'Hoddesdon');
INSERT INTO Clubs (Name, Town) VALUES ('Kimpton Tennis Club', 'Kimpton');
INSERT INTO Clubs (Name, Town) VALUES ('King George V Playing Fields TC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Knebworth TC', 'Knebworth');
INSERT INTO Clubs (Name, Town) VALUES ('Legends Tennis Centre', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Letchworth Sports & TC', 'Letchworth');
INSERT INTO Clubs (Name, Town) VALUES ('Leverstock Green TC', 'Leverstock Green');
INSERT INTO Clubs (Name, Town) VALUES ('Lister Tennis Club', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Little Gaddesden TC', 'Little Gaddesden');
INSERT INTO Clubs (Name, Town) VALUES ('Long Marston TC', 'Long Marston');
INSERT INTO Clubs (Name, Town) VALUES ('Moor Park LTC', 'Rickmansworth');
INSERT INTO Clubs (Name, Town) VALUES ('Much Hadham TC', 'Much Hadham');
INSERT INTO Clubs (Name, Town) VALUES ('Northaw & Cuffley LTC', 'Cuffley');
INSERT INTO Clubs (Name, Town) VALUES ('Northwood TC', 'Northwood');
INSERT INTO Clubs (Name, Town) VALUES ('OA Tennis Club', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Odyssey Health Club', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Offley Tennis Club', 'Offley');
INSERT INTO Clubs (Name, Town) VALUES ('Orchard LTC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Oxhey Hall TC', 'Oxhey');
INSERT INTO Clubs (Name, Town) VALUES ('Pirton Tennis Club', 'Pirton');
INSERT INTO Clubs (Name, Town) VALUES ('Potters Bar TC', 'Potters Bar');
INSERT INTO Clubs (Name, Town) VALUES ('Redbourn TC', 'Redbourn');
INSERT INTO Clubs (Name, Town) VALUES ('Rickmansworth LTC', 'Rickmansworth');
INSERT INTO Clubs (Name, Town) VALUES ('Rothamsted Tennis Club', 'Harpenden');
INSERT INTO Clubs (Name, Town) VALUES ('Royston Tennis Club', 'Royston');
INSERT INTO Clubs (Name, Town) VALUES ('Salisbury Tennis Club Herts', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sarratt Tennis Club', 'Sarratt');
INSERT INTO Clubs (Name, Town) VALUES ('Sawbridgeworth TC', 'Sawbridgeworth');
INSERT INTO Clubs (Name, Town) VALUES ('St Albans LTC', 'St Albans');
INSERT INTO Clubs (Name, Town) VALUES ('St Margaretsbury TC', 'St Margarets');
INSERT INTO Clubs (Name, Town) VALUES ('Standon & Puckeridge LTC', 'Standon');
INSERT INTO Clubs (Name, Town) VALUES ('Tewin Tennis Club', 'Tewin');
INSERT INTO Clubs (Name, Town) VALUES ('Townsend LTC', 'Hertfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Tring LTC', 'Tring');
INSERT INTO Clubs (Name, Town) VALUES ('Watton at Stone TC', 'Watton at Stone');
INSERT INTO Clubs (Name, Town) VALUES ('Welwyn Tennis Club', 'Welwyn');
INSERT INTO Clubs (Name, Town) VALUES ('West Herts & Watford LTC', 'Watford');
INSERT INTO Clubs (Name, Town) VALUES ('Weston Tennis Club', 'Weston');
INSERT INTO Clubs (Name, Town) VALUES ('Wheathampstead LTC', 'Wheathampstead');
INSERT INTO Clubs (Name, Town) VALUES ('Wymondley TC', 'Wymondley');

-- =============================================
-- ESSEX
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Basildon Lawn Tennis Club', '1 Hockley Rd', NULL, 'Basildon', 'SS14 1RP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gidea Park Lawn Tennis Club', 'Gidea Close', NULL, 'Romford', 'RM2 5NP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Colchester', 'United Way', NULL, 'Colchester', 'CO4 6AT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Spring Lane Tennis Club', 'The Chase, Spring Lane', NULL, 'Colchester', 'CO3 4AZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Theydon Bois Lawn Tennis Club', 'Sidney Road', NULL, 'Epping', 'CM16 7DT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Essex Golf & Country Club', NULL, NULL, 'Earls Colne', 'CO6 2NS');
INSERT INTO Clubs (Name, Town) VALUES ('Bentley TC', 'Brentwood');
INSERT INTO Clubs (Name, Town) VALUES ('Billericay LTC', 'Billericay');
INSERT INTO Clubs (Name, Town) VALUES ('Brentwood Hard TC', 'Brentwood');
INSERT INTO Clubs (Name, Town) VALUES ('Brentwood TC', 'Brentwood');
INSERT INTO Clubs (Name, Town) VALUES ('Chelmsfordians TC', 'Chelmsford');
INSERT INTO Clubs (Name, Town) VALUES ('Colchester LTC', 'Colchester');
INSERT INTO Clubs (Name, Town) VALUES ('Connaught Club', 'Epping Forest');
INSERT INTO Clubs (Name, Town) VALUES ('Cranston Park LTC', 'Upminster');
INSERT INTO Clubs (Name, Town) VALUES ('Danbury TC', 'Danbury');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Basildon', 'Basildon');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Gidea Park', 'Romford');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Southend', 'Southend');
INSERT INTO Clubs (Name, Town) VALUES ('Great Baddow LTC', 'Great Baddow');
INSERT INTO Clubs (Name, Town) VALUES ('Grove Chelmsford LTC', 'Chelmsford');
INSERT INTO Clubs (Name, Town) VALUES ('Hadleigh Park LTC', 'Benfleet');
INSERT INTO Clubs (Name, Town) VALUES ('Hamptons Sports & Leisure', 'Chelmsford');
INSERT INTO Clubs (Name, Town) VALUES ('Harlow LTC', 'Harlow');
INSERT INTO Clubs (Name, Town) VALUES ('Hockley LTC', 'Hockley');
INSERT INTO Clubs (Name, Town) VALUES ('Hutton and Shenfield LTC', 'Brentwood');
INSERT INTO Clubs (Name, Town) VALUES ('Ingatestone and Fryerning TC', 'Ingatestone');
INSERT INTO Clubs (Name, Town) VALUES ('Invicta Tennis Club', 'Essex');
INSERT INTO Clubs (Name, Town) VALUES ('Kent Elms TC', 'Southend');
INSERT INTO Clubs (Name, Town) VALUES ('King George V Playing Fields Canvey', 'Canvey Island');
INSERT INTO Clubs (Name, Town) VALUES ('Leigh Road Baptist Church TC', 'Leigh-on-Sea');
INSERT INTO Clubs (Name, Town) VALUES ('Leisure World Tennis Centre', 'Colchester');
INSERT INTO Clubs (Name, Town) VALUES ('Ongar LTC', 'Ongar');
INSERT INTO Clubs (Name, Town) VALUES ('Raphael Park Tennis', 'Romford');
INSERT INTO Clubs (Name, Town) VALUES ('Rochford TC', 'Rochford');
INSERT INTO Clubs (Name, Town) VALUES ('Southend LTC', 'Southend');
INSERT INTO Clubs (Name, Town) VALUES ('Southend Leisure & Tennis Centre', 'Southend');
INSERT INTO Clubs (Name, Town) VALUES ('Southminster TC', 'Southminster');
INSERT INTO Clubs (Name, Town) VALUES ('Stonards Hill Tennis Courts', 'Epping');
INSERT INTO Clubs (Name, Town) VALUES ('The Deanes Sports Centre', 'Essex');
INSERT INTO Clubs (Name, Town) VALUES ('Thorpe Bay LTC', 'Southend');
INSERT INTO Clubs (Name, Town) VALUES ('University of Essex TC', 'Colchester');
INSERT INTO Clubs (Name, Town) VALUES ('Westcliff Hard Court TC', 'Westcliff-on-Sea');
INSERT INTO Clubs (Name, Town) VALUES ('Westcliff LTC', 'Westcliff-on-Sea');
INSERT INTO Clubs (Name, Town) VALUES ('Wickford LTC', 'Wickford');
INSERT INTO Clubs (Name, Town) VALUES ('Woodford Wells', 'Woodford');
INSERT INTO Clubs (Name, Town) VALUES ('Writtle TC', 'Writtle');
INSERT INTO Clubs (Name, Town) VALUES ('Southend Parks Tennis', 'Southend');

-- =============================================
-- BERKSHIRE
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Berkshire County Sports Tennis Club', 'Sonning Lane', NULL, 'Sonning', 'RG4 6ST');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Royal Berkshire', 'Nine Mile Ride', NULL, 'Bracknell', 'RG12 7PB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Royal Ascot Tennis Club', 'Station Hill', NULL, 'Ascot', 'SL5 7HF');
INSERT INTO Clubs (Name, Town) VALUES ('Bracknell LTC', 'Bracknell');
INSERT INTO Clubs (Name, Town) VALUES ('Caversham Park TC', 'Reading');
INSERT INTO Clubs (Name, Town) VALUES ('Crowthorne TC', 'Crowthorne');
INSERT INTO Clubs (Name, Town) VALUES ('Latika Junior Tennis Club', 'Binfield');
INSERT INTO Clubs (Name, Town) VALUES ('Newbury TC', 'Newbury');
INSERT INTO Clubs (Name, Town) VALUES ('Purley on Thames TC', 'Reading');
INSERT INTO Clubs (Name, Town) VALUES ('Sandhurst TC', 'Sandhurst');
INSERT INTO Clubs (Name, Town) VALUES ('Shinfield TC', 'Reading');
INSERT INTO Clubs (Name, Town) VALUES ('Slough TC', 'Slough');
INSERT INTO Clubs (Name, Town) VALUES ('Twyford TC', 'Twyford');
INSERT INTO Clubs (Name, Town) VALUES ('Wargrave TC', 'Reading');
INSERT INTO Clubs (Name, Town) VALUES ('Windsor LTC', 'Windsor');
INSERT INTO Clubs (Name, Town) VALUES ('Wokingham TC', 'Wokingham');

-- =============================================
-- BUCKINGHAMSHIRE
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Aylesbury Tennis Club', 'Wendover Road, Walton', NULL, 'Aylesbury', 'HP21 9NJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bucks Indoor Tennis Centre', 'Holmer Lane', NULL, 'High Wycombe', 'HP12 4UD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Buckingham Lawn Tennis Club', 'Chandos Park, Chandos Road', NULL, 'Buckingham', 'MK18 1AJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Halton Tennis Centre', 'Chestnut End, Halton Village', NULL, 'Aylesbury', 'HP22 5PD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Horsenden Lawn Tennis Club', 'Windsor Playing Fields, Horsenden Lane', NULL, 'Princes Risborough', 'HP27 9NE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('UK Padel Holmer Green', 'Dormer Lane, off Spurland End Road', NULL, 'Holmer Green', 'HP15 6PG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Aylesbury Parks Tennis', 'Bedgrove Park, Ambleside', NULL, 'Aylesbury', 'HP21 9TT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Princes Risborough Tennis Club', 'Hampden Gate, Hampden Road', 'Speen', 'Princes Risborough', 'HP27 0RU');
INSERT INTO Clubs (Name, Town) VALUES ('High Wycombe LTC', 'High Wycombe');
INSERT INTO Clubs (Name, Town) VALUES ('Hambleden TC', 'Hambleden');

-- =============================================
-- OXFORDSHIRE
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Abingdon Lawn Tennis Club', 'Southern Sports Park, Lambrick Way', NULL, 'Abingdon', 'OX14 5TJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Goring Tennis Club', 'Gatehampton Road', NULL, 'Goring-On-Thames', 'RG19 9EP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('White Horse Leisure & Tennis Centre', 'Audlett Drive', NULL, 'Abingdon', 'OX14 3PJ');
INSERT INTO Clubs (Name, Town) VALUES ('Appleton with Eaton TC', 'Appleton');
INSERT INTO Clubs (Name, Town) VALUES ('Ardington and Lockinge TC', 'Ardington');
INSERT INTO Clubs (Name, Town) VALUES ('Bampton TC', 'Bampton');
INSERT INTO Clubs (Name, Town) VALUES ('Banbury LTC', 'Banbury');
INSERT INTO Clubs (Name, Town) VALUES ('Banbury West End LT & Squash Club', 'Banbury');
INSERT INTO Clubs (Name, Town) VALUES ('Benson TC', 'Benson');
INSERT INTO Clubs (Name, Town) VALUES ('Bicester LTC', 'Bicester');
INSERT INTO Clubs (Name, Town) VALUES ('Blewbury TC', 'Blewbury');
INSERT INTO Clubs (Name, Town) VALUES ('Brightwell-cum-Sotwell Kings Meadow TC', 'Brightwell-cum-Sotwell');
INSERT INTO Clubs (Name, Town) VALUES ('Charlbury TC', 'Charlbury');
INSERT INTO Clubs (Name, Town) VALUES ('Chinnor TC', 'Chinnor');
INSERT INTO Clubs (Name, Town) VALUES ('Cholsey TC', 'Cholsey');
INSERT INTO Clubs (Name, Town) VALUES ('Colston LTC', 'Oxfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cropredy TC', 'Cropredy');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Club Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Deddington TC', 'Deddington');
INSERT INTO Clubs (Name, Town) VALUES ('Dorchester TC', 'Dorchester-on-Thames');
INSERT INTO Clubs (Name, Town) VALUES ('Faringdon TC', 'Faringdon');
INSERT INTO Clubs (Name, Town) VALUES ('Hanney TC', 'Hanney');
INSERT INTO Clubs (Name, Town) VALUES ('Harwell Village TC', 'Harwell');
INSERT INTO Clubs (Name, Town) VALUES ('Henley TC', 'Henley-on-Thames');
INSERT INTO Clubs (Name, Town) VALUES ('Hook Norton TC', 'Hook Norton');
INSERT INTO Clubs (Name, Town) VALUES ('Horton-Cum-Studley TC', 'Horton-cum-Studley');
INSERT INTO Clubs (Name, Town) VALUES ('Kingston Bagpuize with Southmoor TC', 'Kingston Bagpuize');
INSERT INTO Clubs (Name, Town) VALUES ('Kings Sutton TC', 'Kings Sutton');
INSERT INTO Clubs (Name, Town) VALUES ('Letcombe TC', 'Letcombe');
INSERT INTO Clubs (Name, Town) VALUES ('Lower Windrush TC', 'Oxfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Norham Gardens LTC', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('North Oxford LTC', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('OUP Sports Ground', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Oxford Sports LTC', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Oxford University LTC', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Peppard LTC', 'Peppard');
INSERT INTO Clubs (Name, Town) VALUES ('Phyllis Court TC', 'Henley-on-Thames');
INSERT INTO Clubs (Name, Town) VALUES ('Portcullis TC', 'Oxfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ramsden Tennis Group', 'Ramsden');
INSERT INTO Clubs (Name, Town) VALUES ('Shillingford & Warborough Tennis Association', 'Shillingford');
INSERT INTO Clubs (Name, Town) VALUES ('Shiplake Tennis and Social Club', 'Shiplake');
INSERT INTO Clubs (Name, Town) VALUES ('Shrivenham LTC', 'Shrivenham');
INSERT INTO Clubs (Name, Town) VALUES ('Sonning Common & District TC', 'Sonning Common');
INSERT INTO Clubs (Name, Town) VALUES ('Stoke Row Sports & Leisure Club Ltd', 'Stoke Row');
INSERT INTO Clubs (Name, Town) VALUES ('Stonesfield TC', 'Stonesfield');
INSERT INTO Clubs (Name, Town) VALUES ('Thame TC', 'Thame');
INSERT INTO Clubs (Name, Town) VALUES ('The Oxfordshire Health & Racquets Club', 'Oxfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Uffington LTC', 'Uffington');
INSERT INTO Clubs (Name, Town) VALUES ('Wantage LTC', 'Wantage');
INSERT INTO Clubs (Name, Town) VALUES ('Watlington TC', 'Watlington');
INSERT INTO Clubs (Name, Town) VALUES ('Witney LTC', 'Witney');
INSERT INTO Clubs (Name, Town) VALUES ('Woodstock Bowls & Tennis Club', 'Woodstock');
INSERT INTO Clubs (Name, Town) VALUES ('Wychwoods TC', 'Oxfordshire');
INSERT INTO Clubs (Name, Town) VALUES ('Alexandra Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Botley Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Boundary Park Didcot', 'Didcot');
INSERT INTO Clubs (Name, Town) VALUES ('Bury Knowle Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Cutteslowe Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Florence Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('Hinksey Park Oxford', 'Oxford');
INSERT INTO Clubs (Name, Town) VALUES ('The Leys Recreation Ground Witney', 'Witney');

-- =============================================
-- SCOTLAND
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Grange Club', 'Portgower Place, Stockbridge', NULL, 'Edinburgh', 'EH4 1HQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Newlands Lawn Tennis Club', '18 Mochrum Road', NULL, 'Glasgow', 'G43 2QE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Whitecraigs LT & Sports Club', 'Ayr Road, Whitecraigs', NULL, 'Glasgow', 'G46 6SJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Craiglockhart Tennis Centre', '177 Colinton Road', NULL, 'Edinburgh', 'EH14 1BZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Aberdeen Tennis Centre', 'Westburn Road', NULL, 'Aberdeen', 'AB25 2DA');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Edinburgh', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Glasgow Renfrew', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Morningside Tennis Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Corstorphine Tennis Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Barnton Park Tennis Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Edinburgh Sports Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Dunbar Tennis Club', 'Dunbar');
INSERT INTO Clubs (Name, Town) VALUES ('Balerno Tennis Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Bathgate Tennis Club', 'Bathgate');
INSERT INTO Clubs (Name, Town) VALUES ('Cramond Tennis Club', 'Edinburgh');
INSERT INTO Clubs (Name, Town) VALUES ('West of Scotland Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Hillpark Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Kelvinside Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Giffnock Tennis Squash & Hockey Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Titwood Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Broomhill Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Bearsden Lawn Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Milngavie Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Clarkston Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Pollokshields Tennis Club', 'Glasgow');
INSERT INTO Clubs (Name, Town) VALUES ('Ayr Tennis Club', 'Ayr');
INSERT INTO Clubs (Name, Town) VALUES ('Prestwick Tennis Club', 'Prestwick');
INSERT INTO Clubs (Name, Town) VALUES ('Troon Tennis Club', 'Troon');
INSERT INTO Clubs (Name, Town) VALUES ('Kilmarnock Tennis Club', 'Kilmarnock');
INSERT INTO Clubs (Name, Town) VALUES ('St Andrews Tennis Club', 'St Andrews');
INSERT INTO Clubs (Name, Town) VALUES ('Cupar Tennis Club', 'Cupar');
INSERT INTO Clubs (Name, Town) VALUES ('Crail Tennis Club', 'Crail');
INSERT INTO Clubs (Name, Town) VALUES ('Dundee Tennis Club', 'Dundee');
INSERT INTO Clubs (Name, Town) VALUES ('Broughty Ferry Tennis Club', 'Dundee');
INSERT INTO Clubs (Name, Town) VALUES ('Perth Tennis Club', 'Perth');
INSERT INTO Clubs (Name, Town) VALUES ('Blairgowrie Tennis Club', 'Blairgowrie');
INSERT INTO Clubs (Name, Town) VALUES ('Stirling Tennis Club', 'Stirling');
INSERT INTO Clubs (Name, Town) VALUES ('Bridge of Allan Tennis Club', 'Bridge of Allan');
INSERT INTO Clubs (Name, Town) VALUES ('Dunblane Tennis Club', 'Dunblane');
INSERT INTO Clubs (Name, Town) VALUES ('Inverness Tennis & Squash Club', 'Inverness');
INSERT INTO Clubs (Name, Town) VALUES ('Fort William Tennis Club', 'Fort William');
INSERT INTO Clubs (Name, Town) VALUES ('Elgin Tennis Club', 'Elgin');
INSERT INTO Clubs (Name, Town) VALUES ('Nairn Tennis Club', 'Nairn');
INSERT INTO Clubs (Name, Town) VALUES ('Peebles Tennis Club', 'Peebles');
INSERT INTO Clubs (Name, Town) VALUES ('Melrose Tennis Club', 'Melrose');
INSERT INTO Clubs (Name, Town) VALUES ('Kelso Tennis Club', 'Kelso');
INSERT INTO Clubs (Name, Town) VALUES ('Hawick Tennis Club', 'Hawick');
INSERT INTO Clubs (Name, Town) VALUES ('Galashiels Tennis Club', 'Galashiels');
INSERT INTO Clubs (Name, Town) VALUES ('Dumfries Tennis Club', 'Dumfries');
INSERT INTO Clubs (Name, Town) VALUES ('Moffat Tennis Club', 'Moffat');
INSERT INTO Clubs (Name, Town) VALUES ('Stranraer Tennis Club', 'Stranraer');
INSERT INTO Clubs (Name, Town) VALUES ('North Berwick Tennis Club', 'North Berwick');
INSERT INTO Clubs (Name, Town) VALUES ('Musselburgh Tennis Club', 'Musselburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Penicuik Tennis Club', 'Penicuik');
INSERT INTO Clubs (Name, Town) VALUES ('Largs Tennis Club', 'Largs');
INSERT INTO Clubs (Name, Town) VALUES ('Helensburgh Tennis Club', 'Helensburgh');
INSERT INTO Clubs (Name, Town) VALUES ('Oban Tennis Club', 'Oban');
INSERT INTO Clubs (Name, Town) VALUES ('Falkirk Tennis Club', 'Falkirk');
INSERT INTO Clubs (Name, Town) VALUES ('Kirkwall Tennis Club', 'Kirkwall');
INSERT INTO Clubs (Name, Town) VALUES ('Lerwick Tennis Club', 'Lerwick');
INSERT INTO Clubs (Name, Town) VALUES ('Stornoway Tennis Club', 'Stornoway');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Aberdeen', 'Aberdeen');
INSERT INTO Clubs (Name, Town) VALUES ('Stonehaven Tennis Club', 'Stonehaven');
INSERT INTO Clubs (Name, Town) VALUES ('Banchory Tennis Club', 'Banchory');
INSERT INTO Clubs (Name, Town) VALUES ('Peterhead Tennis Club', 'Peterhead');

-- =============================================
-- WALES
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cardiff Lawn Tennis Club', 'The Castle Grounds, North Road', NULL, 'Cardiff', 'CF10 3EW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Swansea Tennis and Squash Club', 'Cwm Farm Lane, Sketty', NULL, 'Swansea', 'SA2 9AU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wrexham Tennis Centre', 'Plas Coch Road', NULL, 'Wrexham', 'LL11 2BW');
INSERT INTO Clubs (Name, Town) VALUES ('Penarth Lawn Tennis Club', 'Penarth');
INSERT INTO Clubs (Name, Town) VALUES ('Llantwit Major Tennis Club', 'Llantwit Major');
INSERT INTO Clubs (Name, Town) VALUES ('Romilly Park Tennis Barry', 'Barry');
INSERT INTO Clubs (Name, Town) VALUES ('Newport Tennis Club', 'Newport');
INSERT INTO Clubs (Name, Town) VALUES ('Cwmbran Tennis Club', 'Cwmbran');
INSERT INTO Clubs (Name, Town) VALUES ('Pontypool Tennis Club', 'Pontypool');
INSERT INTO Clubs (Name, Town) VALUES ('Abergavenny Tennis Club', 'Abergavenny');
INSERT INTO Clubs (Name, Town) VALUES ('Monmouth Tennis Club', 'Monmouth');
INSERT INTO Clubs (Name, Town) VALUES ('Neath Tennis Club', 'Neath');
INSERT INTO Clubs (Name, Town) VALUES ('Llanelli Tennis Club', 'Llanelli');
INSERT INTO Clubs (Name, Town) VALUES ('Carmarthen Tennis Club', 'Carmarthen');
INSERT INTO Clubs (Name, Town) VALUES ('Haverfordwest Tennis Club', 'Haverfordwest');
INSERT INTO Clubs (Name, Town) VALUES ('Tenby Tennis Club', 'Tenby');
INSERT INTO Clubs (Name, Town) VALUES ('Pembroke Dock Tennis Club', 'Pembroke Dock');
INSERT INTO Clubs (Name, Town) VALUES ('Aberystwyth Tennis Club', 'Aberystwyth');
INSERT INTO Clubs (Name, Town) VALUES ('Bangor Tennis Club', 'Bangor');
INSERT INTO Clubs (Name, Town) VALUES ('Llandudno Tennis Club', 'Llandudno');
INSERT INTO Clubs (Name, Town) VALUES ('Colwyn Bay Tennis Club', 'Colwyn Bay');
INSERT INTO Clubs (Name, Town) VALUES ('Rhyl Tennis Club', 'Rhyl');
INSERT INTO Clubs (Name, Town) VALUES ('Prestatyn Tennis Club', 'Prestatyn');
INSERT INTO Clubs (Name, Town) VALUES ('Denbigh Tennis Club', 'Denbigh');
INSERT INTO Clubs (Name, Town) VALUES ('Mold Tennis Club', 'Mold');
INSERT INTO Clubs (Name, Town) VALUES ('Connah''s Quay Tennis Club', 'Connah''s Quay');
INSERT INTO Clubs (Name, Town) VALUES ('Welshpool Tennis Club', 'Welshpool');
INSERT INTO Clubs (Name, Town) VALUES ('Newtown Tennis Club', 'Newtown');
INSERT INTO Clubs (Name, Town) VALUES ('Brecon Tennis Club', 'Brecon');
INSERT INTO Clubs (Name, Town) VALUES ('Pontypridd Tennis Club', 'Pontypridd');
INSERT INTO Clubs (Name, Town) VALUES ('Caerphilly Tennis Club', 'Caerphilly');
INSERT INTO Clubs (Name, Town) VALUES ('Bridgend Tennis Club', 'Bridgend');
INSERT INTO Clubs (Name, Town) VALUES ('Port Talbot Tennis Club', 'Port Talbot');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Swansea', 'Swansea');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Cardiff', 'Cardiff');
