-- Part 2: Derbyshire, Lincolnshire, Shropshire, Leicestershire, Northamptonshire, Nottinghamshire, Warwickshire, Staffordshire, Herefordshire & Worcestershire

-- Derbyshire (34 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ashbourne Tennis Club', 'Adjacent to Peak Gateway Leisure Park, Moor Lane', NULL, 'Ashbourne', 'DE6 1NA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ashover Tennis Club', 'Milken Lane, Far Hill', NULL, 'Ashover', 'S45 0BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bamford Tennis Club', 'Water Lane', NULL, 'Bamford', 'S33 0DA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Baslow Lawn Tennis Club', 'Church Lane', NULL, 'Baslow', 'DE45 1SP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Belper Meadows Tennis Club', 'Christ Church Meadows, Bridge Street', NULL, 'Belper', 'DE56 1BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Breadsall Tennis Club', 'Brookside Road', NULL, 'Breadsall', 'DE21 5LF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Buxton Cricket Bowling and Tennis Club', 'Park Road', NULL, 'Buxton', 'SK17 6SF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('CURC Tennis Club', 'Between 25 and 27 Brayfield Road', 'Littleover', 'Derby', 'DE23 6LD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chesterfield LTC', 'Hawksley Avenue, Newbold', NULL, 'Chesterfield', 'S40 4TW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Church Broughton Tennis Club', 'Broughton Heath Golf Course, Bent Lane', NULL, 'Church Broughton', 'DE65 5BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Derby', 'Pride Parkway, Riverside Road', 'Pride Park', 'Derby', 'DE24 8HY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Derbyshire Tennis Centre', 'Ashe Place, Vincent Street', NULL, 'Derby', 'DE23 8BF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Doveridge Tennis Club', 'Playing fields, Off Sand Lane', NULL, 'Doveridge', 'DE6 5JQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Duffield Lawn Tennis Club', '23 Town Street', NULL, 'Duffield', 'DE56 4EH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Etwall Tennis Club', 'Etwall Leisure Centre, Hilton Road', NULL, 'Etwall', 'DE65 6HZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Glossop Tennis Club', 'Pyegrove Road', NULL, 'Glossop', 'SK13 8QS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Holymoorside Tennis Club', 'Holymoor Road', NULL, 'Holymoorside', 'S42 7DX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ilkeston Tennis Club', 'Rutland Sports Park, West End Drive', NULL, 'Ilkeston', 'DE7 5GH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Little Eaton Tennis Club', 'St Peter''s Park, Duffield Road', NULL, 'Little Eaton', 'DE21 5DA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Littleover Tennis Club', '40 Eastwood Drive', NULL, 'Littleover', 'DE23 6BN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Melbourne Lawn Tennis Club', 'Cockshut Lane', NULL, 'Melbourne', 'DE73 8DJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Netherseale Lawn Tennis Club', '2 Hall Farm Cottage', NULL, 'Netherseal', 'DE12 8BZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('New Mills Bowls Cricket and Tennis Club', 'Church Road', NULL, 'New Mills', 'SK22 4NU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ockbrook and Borrowash Lawn Tennis Club', '22 Nottingham Road', NULL, 'Borrowash', 'DE72 3FL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Repton Tennis & Racquets Club', 'Willington Road', NULL, 'Repton', 'DE65 6FH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ridgeway Tennis Club', 'Main Road', NULL, 'Ridgeway', 'S12 3XR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ripley & Alfreton Tennis Club', 'Between 167 & 169 Heage Road', NULL, 'Ripley', 'DE5 3GG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rolls-Royce Tennis Club', 'Moor Lane, Allenton', NULL, 'Derby', 'DE24 9HY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Smalley Lawn Tennis Club', 'Dobholes Lane', NULL, 'Smalley Village', 'DE7 6EL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Grangewood Tennis Centre', 'Lullington Road, Grangewood', NULL, 'Netherseal', 'DE12 8BE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tideswell Tennis Club', 'St John''s Road, Tideswell Sports Complex', NULL, 'Tideswell', 'SK17 8NE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('We are Padel Derby', 'Derwent Parade', NULL, 'Derby', 'DE24 8BW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wingerworth Tennis Club', 'Allendale Road', NULL, 'Wingerworth', 'S42 6PX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodlands Tennis Club', 'Kedleston Road', NULL, 'Allestree', 'DE22 2TG');

-- Lincolnshire (35 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bannatyne Humberston Club', 'Humberston Avenue', NULL, 'Humberston', 'DN36 4SX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Boston Tennis Club', '125 Sleaford Road', NULL, 'Boston', 'PE21 8EY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bourne Lawn Tennis Club', 'The Monks Garden, Abbey Lawn', NULL, 'Bourne', 'PE10 9EN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Brigg Tennis Club', 'Wrawby Road', NULL, 'Brigg', 'DN20 8DT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Caistor Lawn Tennis Club', 'Sportsground, Brigg Road', NULL, 'Market Rasen', 'LN7 6RX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Lincoln', 'Woodcock Lane', NULL, 'Lincoln', 'LN1 2BE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Deeping Tennis Club', 'Outgang Road', NULL, 'Peterborough', 'PE6 8LQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Doddington Hall Tennis Club', 'Doddington Hall', 'Doddington', 'Lincoln', 'LN6 4RU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eastgate Club Lincoln', 'Langworthgate', NULL, 'Lincoln', 'LN2 4AD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Epworth Tennis Club', 'Epworth War Memorial Field, Station Road', NULL, 'Doncaster', 'DN9 1JZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Grantham Tennis Club and Gym', 'Arnoldfield, Gonerby Road', NULL, 'Grantham', 'NG31 8HU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Grimsby Tennis Centre', '17 Weelsby Avenue', NULL, 'Grimsby', 'DN32 0AH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Haxey Tennis Club', 'Haxey Lane', NULL, 'Doncaster', 'DN9 2ND');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Heckington Tennis Club', 'Off Churchill Way, Heckington', NULL, 'Sleaford', 'NG34 9RQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Horncastle and District Lawn Tennis Club', 'Courtside', NULL, 'Horncastle', 'LN9 6HP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Keelby Tennis Club', 'Stallingborough Road', NULL, 'Grimsby', 'DN41 8JA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Leadenham Tennis Club', 'Leadenham Playing Fields, Main Road', NULL, 'Lincoln', 'LN5 0QB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lincoln Tennis Academy', 'Village Hall, Honeyholes Lane', 'Dunholme', 'Lincoln', 'LN2 3SU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Louth Tennis & Sports Centre', 'Plot 10, Scarborough Road', NULL, 'Louth', 'LN11 0WD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nettleham Tennis Club', 'Mulsanne Park, Mill Hill', NULL, 'Lincoln', 'LN2 2RX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('North Scarle Tennis Club', 'South Scarle Lane', 'North Scarle', 'Lincoln', 'LN6 9ER');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Reepham and District Tennis Club', 'Hawthorn Road', NULL, 'Lincoln', 'LN3 4DU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rustons Tennis Club', 'RMSC Sportsground, Newark Road', NULL, 'Lincoln', 'LN6 8RN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Saxilby Tennis Club', 'William Street, Saxilby', NULL, 'Lincoln', 'LN1 2LP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Scotter Tennis Club', 'The Playing Field, Scotter', NULL, 'Gainsborough', 'DN21 3RY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sleaford Tennis Club', 'Boston Road', NULL, 'Sleaford', 'NG34 7EZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Spalding Town Tennis Club', 'Holyrood Walk, Off Clay Lane', NULL, 'Spalding', 'PE11 2RY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Spilsby and District Tennis and Croquet Club', 'Hundleby Road', NULL, 'Spilsby', 'PE23 5NH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('St James Tennis Club', 'Hereford Avenue', NULL, 'Grimsby', 'DN34 5BL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stamford Tennis Club', 'Northfields Court, Conduit Road', NULL, 'Stamford', 'PE9 1RA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tattershall Tennis Club', 'Lodge Road', NULL, 'Lincoln', 'LN4 4JS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tealby Tennis & Bowls Club', 'Rasen Road, Tealby', NULL, 'Market Rasen', 'LN8 3XL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Vida del Padel Lincoln', 'Unit C4, Bishops Trade Park', NULL, 'Lincoln', 'LN2 4ZS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Washingborough Tennis Club', 'Playing Fields, Fen Road', 'Washingborough', 'Lincoln', 'LN4 1AB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodhall Spa Tennis Club', 'Jubilee Park, Stixwould Road', NULL, 'Woodhall Spa', 'LN10 5HJ');

-- Shropshire (36 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Albrighton Tennis Club', 'Kennel Lane', NULL, 'Albrighton', 'WV7 3BQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Alveley Lawn Tennis Club', NULL, NULL, 'Alveley', 'WV15 6JT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Baschurch Tennis Club', NULL, NULL, 'Baschurch', 'SY4 2EG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bishops Castle Tennis Club', 'Love Lane', NULL, 'Bishops Castle', 'SY9 5DW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bomere Heath Tennis Club', 'Shrewsbury Road', NULL, 'Bomere Heath', 'SY4 3PD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Boughey Gardens Tennis Club', '17a High Street', NULL, 'Newport', 'TF10 7AR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bridgnorth Tennis Club', 'Cricket Meadow, Off Victoria Road', NULL, 'Bridgnorth', 'WV16 4LA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Broseley Tennis Club', 'Duke Street', NULL, 'Broseley', 'TF12 5LY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Church Stretton Lawn Tennis Club', 'Church Stretton Town Park', NULL, 'Church Stretton', 'SY6 7JH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Claverley Tennis Club', 'Church Street', NULL, 'Claverley', 'WV5 7DS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cound And District Tennis Club', 'Cound', NULL, 'Shrewsbury', 'SY5 6AR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Criftins Tennis Club', 'Criftins Parish Hall, Dudleston Heath', NULL, 'Ellesmere', 'SY1 4RQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hanmer Tennis Club', 'Sandy Lane', NULL, 'Whitchurch', 'SY13 3DL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('High Ercall Tennis Club', 'Newport Road', NULL, 'High Ercall', 'TF6 6AE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hinstock Tennis Club', 'Recreation Ground, Chester Road', NULL, 'Hinstock', 'TF9 2TE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hollies Tennis Club', 'Tarporley Road', NULL, 'Whitchurch', 'SY13 1LP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lilleshall Village Tennis Club', 'Hilside East', NULL, 'Lilleshall', 'TF10 9GZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Llanymynech Tennis Club', 'Village Hall, Station Road', NULL, 'Llanymynech', 'SY22 6EE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Longden Tennis Club', 'Douglas Squire Memorial Hall', NULL, 'Longden', 'SY5 8EX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ludlow Castle Tennis Club', 'The Linney', NULL, 'Ludlow', 'SY8 1EE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Market Drayton Tennis Club', 'Greenfields Lane, Adderley Road', NULL, 'Market Drayton', 'TF9 3SL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Norton In Hales Tennis Club', 'Bearstone Road', NULL, 'Norton In Hales', 'TF9 4AP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oswestry Team Tennis', 'Cae Glas Park, Church Street', NULL, 'Oswestry', 'SY11 2SZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oswestry Tennis Club', 'Welsh Walls', NULL, 'Oswestry', 'SY11 1RW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rowton Castle Tennis Club', 'Rowton, Halfway House', NULL, 'Shrewsbury', 'SY5 9EP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Shifnal Tennis Club', 'Priorslee Road', NULL, 'Shifnal', 'TF11 8HD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Shrewsbury Lawn Tennis', 'Crescent Lane, Off Town Wall', NULL, 'Shrewsbury', 'SY1 1TR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Telford Tennis Centre', 'Oakengates Leisure Centre, New Road', 'Wrockwardine Wood', 'Telford', 'TF2 7AB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Shrewsbury Club', 'Sundorne Road', NULL, 'Shrewsbury', 'SY1 4RQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tilstock Bowling and Tennis Club', 'Tilstock', NULL, 'Whitchurch', 'SY13 3JL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Town Walls Tennis Club', 'Crescent Lane', NULL, 'Shrewsbury', 'SY1 1TN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wem Tennis Club', 'The Recreation Ground, Park Road', NULL, 'Wem', 'SY4 5DA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodfield Tennis Club', 'Woodfield Road', NULL, 'Shrewsbury', 'SY3 8LU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woore Tennis Club', 'London Road', NULL, 'Woore', 'CW3 9SF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Worfield Tennis Club', 'Hallon', NULL, 'Worfield', 'WV15 5JZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wrekin & Telford Tennis Community', 'Oakengates Leisure Center, New Road', 'Wrockwardine Wood', 'Telford', 'TF2 7AB');

-- Leicestershire (49 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Anstey Gynsill Tennis Club', 'Cnr of Gynsill Close & Gorse Hill', NULL, 'Anstey', 'LE7 7AN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ashby Castle Lawn Tennis Club', 'Off South Street', 'Adjacent to Ashby Castle', 'Ashby-de-la-Zouch', 'LE65 1BQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Beacon Tennis Club', 'King George Playing Fields', NULL, 'Woodhouse Eaves', 'LE12 8RZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Belvoir Vale Tennis Club', NULL, NULL, 'Hose', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Birstall Watermead Tennis Club', 'Off Redhill Circle', NULL, 'Birstall', 'LE4 4DE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blaby Victoria Tennis Club', 'Leicester Road', NULL, 'Blaby', 'LE8 4GQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Burton-on-the-Wolds Tennis Club', 'c/o 17 Springfield Close', NULL, 'Burton-on-the-Wolds', 'LE12 5AN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Carisbrooke Lawn Tennis Club', 'Kenwood Road, Off Carisbrooke Road', NULL, 'Leicester', 'LE2 3PF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Charnwood Lawn Tennis Club', 'Nanpantan Sports Ground, Nanpantan Road', NULL, 'Loughborough', 'LE11 3TN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Narborough', NULL, NULL, 'Narborough', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Desford Lawn Tennis Club', 'The Flying Fields, Peckleton Lane', NULL, 'Desford', 'LE9 9JU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Enderby Lawn Tennis Club', 'Mill Lane', NULL, 'Enderby', 'LE19 4LX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Foxton Tennis Club', 'Recreation Field, Middle Street', NULL, 'Foxton', 'LE16 7RE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Great Glen Tennis Club', 'C/O 1 Sence Crescent', NULL, 'Great Glen', 'LE8 9DU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hamilton Lawn Tennis Club', NULL, NULL, 'Hamilton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hinckley Town Tennis Club', 'Leicester Road Sports Ground', NULL, 'Hinckley', 'LE10 3DR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Holwell Sports Tennis Club', 'Welby Road, Asfordby Hill', NULL, 'Melton Mowbray', 'LE14 3RE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Houghton Tennis Club', 'Houghton Playing Fields, End of Weir Lane', NULL, 'Houghton on the Hill', 'LE7 9GR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Husbands Bosworth Tennis Club', 'Playing Fields, Kilworth Road', NULL, 'Husbands Bosworth', 'LE17 6JY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kegworth Tennis Club', 'King George V Playing Fields, Nottingham Road', NULL, 'Kegworth', 'DE74 2FH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ketton Tennis Club', 'Ketton Sports & Community Centre, Pit Lane', NULL, 'Ketton', 'PE9 3SZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kibworth Tennis Club', NULL, NULL, 'Kibworth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Knighton Tennis Centre', 'Knighton Lane East', NULL, 'Leicester', 'LE2 6FU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Leicester Forest East Tennis Club', 'Hinckley Road', NULL, 'Leicester Forest East', 'LE3 3PJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Leicestershire Tennis & Squash Club', 'Park Lane', 'Stoneygate', 'Leicester', 'LE2 2BT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Loughborough Greenfields Tennis Club', 'Holt Drive', NULL, 'Loughborough', 'LE11 3HZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Loughborough Lawn Tennis Club', 'Ingle Pingle, Off Forest Road', NULL, 'Loughborough', 'LE11 3NW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Loughborough University Tennis', 'Epinal Way', NULL, 'Loughborough', 'LE11 3TU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lutterworth Tennis Club', 'Hall Park, Hall Lane', NULL, 'Lutterworth', 'LE17 4LN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Market Bosworth Tennis Club', 'Dixie Grammar School Playing Fields, Barton Road', NULL, 'Market Bosworth', 'CV13 0LQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Market Harborough Lawn Tennis Club', 'Recreation Ground, Station Road', 'Great Bowden', 'Market Harborough', 'LE16 7HL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Medbourne Tennis Club', 'Medbourne Sports Club, Hallaton Road', NULL, 'Market Harborough', 'LE16 8DR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Melton Mowbray Tennis Club', 'Tennis Avenue, Off Sandy Lane', NULL, 'Melton Mowbray', 'LE13 0RB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Newtown Linford Tennis Club', NULL, NULL, 'Newtown Linford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oadby Granville Tennis Club', NULL, NULL, 'Oadby', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oakham Tennis Club', 'The Vale, Off Uppingham Road', NULL, 'Oakham', 'LE15 6JQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oaks & District Tennis Club', 'Oaks Road, Oaks In Charnwood', NULL, 'Loughborough', 'LE12 9YD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rothley Ivanhoe Tennis Club', NULL, NULL, 'Rothley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Roundhill Tennis Club', NULL, NULL, 'Leicestershire', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rutland Tennis Academy', NULL, NULL, 'Rutland', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sileby Tennis Club', NULL, NULL, 'Sileby', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stoney Stanton Tennis Club', 'War Memorial Playing Fields, Off Carey Hill Road', NULL, 'Stoney Stanton', 'LE9 4TD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Syston Northfields Tennis Club', 'Northfields, Melton Road', NULL, 'Syston', 'LE7 1HW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tilton and District Sports Club', 'The Mill House, Melton Road', NULL, 'Tilton on the Hill', 'LE7 9LG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('University of Leicester Tennis', NULL, NULL, 'Leicester', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Victoria Tennis Club Leicester', 'Park Lane', 'Stoneygate', 'Leicester', 'LE2 2BT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Welland Park Tennis Club', 'Welland Park Road', NULL, 'Market Harborough', 'LE16 9DR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Westfields Tennis Club', '21A Eastfield Road, Off Hinckley Road', NULL, 'Leicester', 'LE3 6FE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wigston Tennis Club', 'Horsewell Lane, Little Lane', NULL, 'Wigston', 'LE18 2HQ');

-- Northamptonshire (26 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Abington Lawn Tennis Club', 'Park Avenue South', NULL, 'Northampton', 'NN3 3AA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blakesley Tennis Club', 'Playing Fields', NULL, 'Towcester', 'NN12 8RN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Brackley Tennis Club', 'Westminster Road', NULL, 'Brackley', 'NN13 7EB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Brixworth Tennis Club', 'Haywards Barns', NULL, 'Northampton', 'NN6 9DQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Byfield Tennis Club', 'Brightwell Recreation Ground', NULL, 'Daventry', 'NN11 6UT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Collingtree Tennis Club', 'The Playing Field, Northampton Road', NULL, 'Northampton', 'NN6 7AR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Corby Tennis Centre', 'Jimmy Kane Way, Rockingham Road', NULL, 'Corby', 'NN17 2FB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Crick and West Haddon Tennis', NULL, NULL, 'Crick', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Dallington Lawn Tennis Club', 'Dallington Park Road, Dallington', NULL, 'Northampton', 'NN5 7AA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Duston Tennis Club', 'Mendip Road, Duston', NULL, 'Northampton', 'NN5 6BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ferrers and Rushden Tennis Club', 'Recreation Ground, Wharf Road', 'Higham Ferrers', 'Rushden', 'NN10 8EP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Guilsborough Tennis Club', 'Guilsborough Academy, West Haddon Road', NULL, 'Northampton', 'NN6 8QE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harpole Tennis Club', NULL, NULL, 'Harpole', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kettering Tennis Club', 'Northampton Road Tennis Courts, Lake Avenue', NULL, 'Kettering', 'NN15 6PB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kilsby Tennis Club', NULL, NULL, 'Kilsby', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kings Cliffe Tennis Club', 'Kingsmead, Station Road', NULL, 'Kings Cliffe', 'PE8 6YH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kings Park Tennis Centre', 'King''s Park Road', NULL, 'Northampton', 'NN3 6LL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Middleton Cheney Tennis Club', NULL, NULL, 'Middleton Cheney', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nether Heyford Tennis Club', NULL, NULL, 'Nether Heyford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Northampton County Lawn Tennis Club', '54B Church Way, Weston Favell', NULL, 'Northampton', 'NN3 3BX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Northampton Lawn Tennis Club', 'Westwood Way', NULL, 'Northampton', 'NN3 3HH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oundle Tennis Club', 'Benefield Road', NULL, 'Oundle', 'PE8 4EZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Roade Tennis Club', NULL, NULL, 'Roade', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rushmere Tennis Club', NULL, NULL, 'Northamptonshire', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Thrapston & District Tennis Club', NULL, NULL, 'Thrapston', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Towcestrians Tennis Club', 'Greens Norton Road', NULL, 'Towcester', NULL);

-- Nottinghamshire (41 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bingham Lawn Tennis Club', 'The Banks', NULL, 'Bingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Burton Joyce Lawn Tennis Club', 'Cragmoor Road', NULL, 'Burton Joyce', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chilwell Memorial Tennis Club', '129 High Road', NULL, 'Chilwell', 'NG9 4AT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd West Bridgford', 'Farnborough Road', NULL, 'Nottingham', 'NG11 8LJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Mansfield Lawn Tennis Club', 'Pheasant Hill, Chesterfield Road', NULL, 'Mansfield', 'NG19 7AL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Mapperley Park Tennis Club', 'Carisbrooke Drive', NULL, 'Nottingham', 'NG3 5DS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nottingham Tennis Centre', 'University Boulevard', NULL, 'Nottingham', 'NG7 2QH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Park Tennis Club', '7 Tattershall Drive, The Park', NULL, 'Nottingham', 'NG7 1BX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('West Bridgford Tennis Club', 'Little Bounds, Wilford Lane', NULL, 'West Bridgford', 'NG2 7QA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lady Bay Tennis and Sports Club', 'Gertrude Road', NULL, 'West Bridgford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Aslockton Tennis Club', NULL, NULL, 'Aslockton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Attenborough Lawn Tennis Club', NULL, NULL, 'Attenborough', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Caunton Lawn Tennis Club', NULL, NULL, 'Caunton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Collingham Lawn Tennis Club', 'Dale Field, Cottage Lane', NULL, 'Collingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Nottingham', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('East Bridgford Tennis Club', NULL, NULL, 'East Bridgford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eastwood LTC', NULL, NULL, 'Eastwood', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Epperstone Sports and Leisure Club', NULL, NULL, 'Epperstone', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Farnsfield Lawn Tennis Club', 'New Hill', NULL, 'Farnsfield', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ilkeston Lawn Tennis Club', NULL, NULL, 'Ilkeston', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Keyworth & District LTC', 'Elm Avenue', NULL, 'Keyworth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lakeside Lawn Tennis Club', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Magdala Lawn Tennis Club', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Musters Tennis Club', NULL, NULL, 'West Bridgford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Newark Lawn Tennis Club', 'London Road', NULL, 'Newark', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nottingham Castle Lawn Tennis Club', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nottingham Trent University Tennis', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ravenshead Lawn Tennis Club', 'Longdale Lane', NULL, 'Ravenshead', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Retford Lawn Tennis Club', NULL, NULL, 'Retford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Southwell Lawn Tennis Club', NULL, NULL, 'Southwell', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sutton Bonington Tennis Club', NULL, NULL, 'Sutton Bonington', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sutton-in-Ashfield Tennis Club', NULL, NULL, 'Sutton-in-Ashfield', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('University of Nottingham Tennis', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Upper Broughton Youth and Social Club', NULL, NULL, 'Upper Broughton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Upper Saxondale Tennis Club', NULL, NULL, 'Radcliffe-on-Trent', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Welbeck Tennis Club', NULL, NULL, 'Welbeck', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wheatley Tennis Club', NULL, NULL, 'Nottingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wollaton Village Tennis Club', NULL, NULL, 'Wollaton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodborough Tennis Club', NULL, NULL, 'Woodborough', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodthorpe Tennis Club', NULL, NULL, 'Woodthorpe', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kingsway Park Tennis Courts', NULL, NULL, 'Nottingham', NULL);

-- Warwickshire (6 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Edgbaston Priory Club', 'Sir Harrys Road', 'Edgbaston', 'Birmingham', 'B15 2UZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('West Warwickshire Sports Club', 'Grange Road', NULL, 'Solihull', 'B91 1DA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Warwick Tennis Club', 'Hampton Road', NULL, 'Warwick', 'CV34 6HX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Coventry & North Warwickshire Sports Club', 'Binley Road', NULL, 'Coventry', 'CV3 1HB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Warwick Boat Club', 'Mill End', NULL, 'Warwick', 'CV34 5JB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Nuneaton Lawn Tennis Club', 'Weddington Road', NULL, 'Nuneaton', 'CV10 0AD');

-- Staffordshire (5 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stone Lawn Tennis & Squash Club', '117 Newcastle Road', NULL, 'Stone', 'ST15 8LD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Walton Tennis Club', 'Green Gore Lane, Milford Road', NULL, 'Stafford', 'ST17 0LD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stafford Manor Indoor Tennis Centre', 'Wolverhampton Road', NULL, 'Stafford', 'ST17 9DJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Basford Lawn Tennis Club', NULL, NULL, 'Newcastle-under-Lyme', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Grange Lawn Tennis Club', NULL, NULL, 'Burton-on-Trent', NULL);

-- Herefordshire (12 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hereford Squash Tennis & Racketball Centre', 'Sollars Close', NULL, 'Hereford', 'HR4 0LX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bodenham Tennis Club', NULL, NULL, 'Bodenham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eardisley Tennis and Croquet Club', NULL, NULL, 'Eardisley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Goodrich Tennis Club', NULL, NULL, 'Goodrich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ledbury Lawn Tennis Club', NULL, NULL, 'Ledbury', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ross Tennis Centre', NULL, NULL, 'Ross-on-Wye', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Leominster Tennis Club', NULL, NULL, 'Leominster', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wellington Tennis Club', NULL, NULL, 'Wellington', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Madley Tennis Club', NULL, NULL, 'Madley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woolhope Tennis Club', NULL, NULL, 'Woolhope', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Preston-on-Wye Sports Club', NULL, NULL, 'Preston-on-Wye', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kington Tennis Club', NULL, NULL, 'Kington', NULL);

-- Worcestershire (29 clubs, duplicates removed)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Boughton Park Lawn Tennis Club', NULL, NULL, 'Worcester', 'WR2 4EZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hallow Lawn Tennis Club', 'Main Road', NULL, 'Hallow', 'WR2 6PW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kempsey Lawn Tennis Club', 'The Playing Fields, Plovers Rise', NULL, 'Kempsey', 'WR5 3SA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Manor Park Sports Club', 'Albert Road North', NULL, 'Malvern', 'WR14 2TL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Worcester Lawn Tennis Club', 'Northwick Close', NULL, 'Worcester', 'WR3 7EF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Alfrick and Lulsley Tennis Club', NULL, NULL, 'Alfrick', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Barnt Green Sports Club', NULL, NULL, 'Barnt Green', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Belbroughton Tennis Club', NULL, NULL, 'Belbroughton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bewdley Tennis Club', NULL, NULL, 'Bewdley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blakedown & Hagley Tennis Club', NULL, NULL, 'Hagley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bromsgrove Tennis Club', NULL, NULL, 'Bromsgrove', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cookley Lawn Tennis Club', NULL, NULL, 'Cookley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cutnall Green Tennis Club', NULL, NULL, 'Cutnall Green', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Bromsgrove', NULL, NULL, 'Bromsgrove', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Worcester', NULL, NULL, 'Worcester', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Droitwich Tennis Club', NULL, NULL, 'Droitwich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Evesham Tennis Club', NULL, NULL, 'Evesham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Far Forest Tennis Club', NULL, NULL, 'Far Forest', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Fladbury Tennis Club', NULL, NULL, 'Fladbury', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Inkberrow Tennis Club', NULL, NULL, 'Inkberrow', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kidderminster Tennis Club', NULL, NULL, 'Kidderminster', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Littletons Tennis Club', NULL, NULL, 'Worcestershire', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Mathon Cradley and Storridge Tennis Club', NULL, NULL, 'Cradley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ombersley & Doverdale Tennis Club', NULL, NULL, 'Ombersley', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Pershore Tennis Centre', NULL, NULL, 'Pershore', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Redditch Tennis Club', NULL, NULL, 'Redditch', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stourport Tennis and Squash Club', NULL, NULL, 'Stourport-on-Severn', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Lenches Tennis Club', NULL, NULL, 'Worcestershire', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wythall Tennis Club', NULL, NULL, 'Wythall', NULL);
