-- Part 3: Cumbria, Durham & Cleveland, Northumberland, Isle of Man, Yorkshire

-- =============================================
-- CUMBRIA (28 clubs)
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Anthorn Sports Club', 'Anthorn', NULL, 'Wigton', 'CA7 5AJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Appleby Tennis Club', 'Appleby Grammar School, Battlebarrow', NULL, 'Appleby-in-Westmorland', 'CA16 6XU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Arnside Tennis Club', 'Silverdale Road, Arnside', NULL, 'Carnforth', 'LA5 0DZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bitts Park Carlisle', 'Parks Depot, Dacre Street', NULL, 'Carlisle', 'CA3 8UZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Broughton-In-Furness Tennis Club', 'High Kepplewray', NULL, 'Broughton-In-Furness', 'LA20 6BL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Burneside Tennis Club', 'Sharps Lane, Burneside', NULL, 'Kendal', 'LA9 6RA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chatsworth Tennis Club', 'St. Aidans Road', NULL, 'Carlisle', 'CA1 1LS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Crosthwaite & Lyth Tennis Club', 'Milldam Barn Crook', NULL, 'Kendal', 'LA8 8LR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Dalston LTC', 'Dalston Recreation Ground, Dalston', NULL, 'Carlisle', 'CA5 7QD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eden Lawn Tennis Club', 'Brampton Road', NULL, 'Carlisle', 'CA3 9AN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harrington Lawn Tennis Club', 'Harrington', NULL, 'Workington', 'CA14 5PS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hawcoat Park Sports Club', 'Hawcoat Lane', NULL, 'Barrow-in-Furness', 'LA14 4HF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Heversham With Milnthorpe Tennis Club', 'Dallam School', NULL, 'Heversham', 'LA7 7EH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kendal LTC', NULL, NULL, 'Kendal', 'LA9 6HF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Keswick & Braithwaite LTC', 'Braithwaite', NULL, 'Keswick', 'CA12 5RY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kirkbride Tennis Club', 'Kirkbride Tennis Club', NULL, 'Wigton', 'CA7 9RG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kirkby Lonsdale Tennis Club', 'Queen Elizabeth School, Kirkby Lonsdale', NULL, 'Carnforth', 'LA6 2HJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lorton LTC', 'High Lorton', NULL, 'Cockermouth', 'CA13 9UL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lunesdale Sports Centre', 'Kendal Road, Kirkby Lonsdale', NULL, 'Carnforth', 'LA6 2HJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Maryport Tennis Club', 'Netherhall School, Netherhall Road', NULL, 'Maryport', 'CA15 6NT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('North Lonsdale Tennis Club', 'Yew Tree Playing Fields', NULL, 'Grange-over-Sands', 'LA11 7AA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Patterdale Tennis & Croquet Club', 'King George V Playing Field, Patterdale', NULL, 'Penrith', 'CA11 0PJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Penrith Castle Park', 'Ullswater Road', NULL, 'Penrith', 'CA11 7JH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Seascale Tennis Club', 'Gosforth Road', NULL, 'Seascale', 'CA20 1JG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sedbergh Tennis Club', 'Guldrey Lane', NULL, 'Sedbergh', 'LA10 5DE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Silloth-On-Solway LTC', 'Skinburness Road', NULL, 'Wigton', 'CA7 4DX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ulverston Tennis Club', 'Ulverston Leisure Centre, Priory Road', NULL, 'Ulverston', 'LA12 9HT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Whitehaven Community Tennis Club', 'St Benedict''s Catholic High School, Red Lonning', NULL, 'Whitehaven', 'CA28 8UG');

-- =============================================
-- DURHAM & CLEVELAND (29 clubs)
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bishop Auckland Tennis Club', 'Town Recreation Ground', NULL, 'Bishop Auckland', 'DL14 7DD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blaydon Tennis Club', 'Spa Well Road', 'Swalwell', 'Swalwell', 'NE21 6JA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Boldon LTC', 'Dipe Lane', 'East Boldon', 'East Boldon', 'NE36 0PQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chilton & Sedgefield Tennis Club', 'Eden Lane Park, Eden Lane', NULL, 'Peterlee', 'SR8 5DJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Sunderland', 'Camberwell Way', 'Doxford Park', 'Sunderland', 'SR3 3XN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Teesside', 'Tees Barrage Way', 'Thornaby', 'Thornaby', 'TS17 6QA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Durham Archery LTC', 'Clay Lane', NULL, 'Durham', 'DH1 4QL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Durham Moor Tennis Club', 'Durham Moor Crescent', 'Durham Moor', 'Durham', 'DH1 5AW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eldon Grove Tennis Club', 'Eldon Grove', NULL, 'Hartlepool', 'TS26 9LY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Great Broughton & Kirby Sports Club', 'Kirby Lane', NULL, 'Great Broughton', 'TS9 7HG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Greenfield Tennis Club', 'Greenfield Community College', NULL, 'Newton Aycliffe', 'DL5 7LF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Guisborough Tennis Club', 'Howlbeck Road', NULL, 'Guisborough', 'TS14 6LE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hartlepool Tennis Club', 'Granville Avenue', NULL, 'Hartlepool', 'TS26 8NE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hutton Rudby Tennis Club', 'Belbrough Lane', NULL, 'Hutton Rudby', 'TS15 0HP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lanchester LTC', 'Fort Road', NULL, 'Lanchester', 'DH7 0SE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('New Blackwell LTC', 'Carmel Grove', NULL, 'Darlington', 'DL3 8EQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('New Silksworth Tennis Club', 'Silksworth Lane', NULL, 'Sunderland', 'SR3 1PD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Norton LTC', 'Station Road', NULL, 'Norton', 'TS20 1PE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Saltburn Tennis Club', 'Marske Mill Lane', NULL, 'Saltburn', 'TS12 1HJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Shotley & Benfieldside Tennis Club', 'Benfield Close', NULL, 'Shotley Bridge', 'DH8 0RH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('South Shields Tennis Club', 'Dean Road', NULL, 'South Shields', 'NE33 4EA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sunderland Tennis Centre', 'Silksworth Lane', NULL, 'Sunderland', 'SR3 1PD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tennis World Middlesbrough', 'Marton Road', NULL, 'Middlesbrough', 'TS4 3SA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wellfield Tennis Club', 'Mill Lane', NULL, 'High Coniscliffe', 'DL2 2LH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Yarm Tennis Club', 'Leven Road', NULL, 'Yarm', 'TS15 9EY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Barnard Castle LTC', NULL, NULL, 'Barnard Castle', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Billingham Tennis Club', NULL, NULL, 'Billingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Burnmoor Tennis Club', NULL, NULL, 'Durham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('NE Visually Impaired Tennis Club', NULL, NULL, 'Durham', NULL);

-- =============================================
-- NORTHUMBERLAND (28 clubs)
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Allendale Tennis Club', 'Allen Mill, Allendale', NULL, 'Hexham', 'NE47 9EQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Alnwick Tennis Club', 'Prudhoe Street', NULL, 'Alnwick', 'NE66 1UH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Berwick Tennis Club', 'Pier Fields, Devon Terrace', NULL, 'Berwick-upon-Tweed', 'TD15 1JE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Beverley Park Lawn Tennis Club', 'Beverley Road', NULL, 'Whitley Bay', 'NE25 8JH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blyth Ridley Tennis Club', '46 Albatross Way', 'South Beach Estate', 'Blyth', 'NE24 3QH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Collingwood Tennis Club', 'Priors Park, Prior''s Terrace', NULL, 'North Shields', 'NE30 4BE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Corbridge Tennis Club Ltd', 'Tynedale Park, Station Road', NULL, 'Corbridge', 'NE45 5BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cramlington Community Tennis', 'Alexandra Park, Ganton Avenue', 'Southfield Green', 'Cramlington', 'NE23 6EL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cullercoats Lawn Tennis Club', 'Beverley Gardens, Cullercoats', NULL, 'North Shields', 'NE30 4NS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Newcastle', 'Castle Farm Road', 'South Gosforth', 'Newcastle upon Tyne', 'NE3 1SN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Forest Hall Community Tennis Club', 'Springfield Road', 'Forest Hall', 'Newcastle upon Tyne', 'NE12 9AG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gosforth Bohemians Tennis Club', 'South Ridge, Brunton Park', NULL, 'Newcastle upon Tyne', 'NE3 2EJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gosforth Garden Village', 'Rosewood Avenue, Gosforth', NULL, 'Newcastle upon Tyne', 'NE3 5DD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gosforth Lawn Tennis Club', 'West Avenue, Gosforth', NULL, 'Newcastle upon Tyne', 'NE3 4ES');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hexham Tennis and Padel Club', 'Priors Flat', NULL, 'Hexham', 'NE46 3EW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Jesmond Lawn Tennis Club', '102 Osborne Road, Jesmond', NULL, 'Newcastle upon Tyne', 'NE2 2TD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Morpeth Tennis Club', 'Morpeth Hockey Cricket & Tennis Club', 'Longhirst', 'Morpeth', 'NE61 3LL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Northumberland Tennis Academy', 'North Jesmond Avenue, Jesmond', NULL, 'Newcastle upon Tyne', 'NE2 3JU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ponteland Community Primary School Tennis', 'Callerton Lane, Ponteland', NULL, 'Newcastle upon Tyne', 'NE20 9EY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ponteland Lawn Tennis Club', 'Memorial Hall Complex, Darras Road', 'Ponteland', 'Newcastle upon Tyne', 'NE20 9NX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Riding Mill Tennis Club', 'Millfield Road', NULL, 'Riding Mill', 'NE44 6DL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rockcliffe Bowling & Tennis Club', 'Victoria Park, Promenade', 'Whitley Bay', 'Whitley Bay', 'NE26 2BB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Rothbury Tennis Club', 'Riverside', NULL, 'Morpeth', 'NE65 7NS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stocksfield & District Tennis Club', 'Guessburn', NULL, 'Stocksfield', 'NE43 7QS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tennis at Churchill', 'Churchill Community College, Churchill Street', 'Wallsend', 'Wallsend', 'NE28 7TN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Northumberland Club', 'North Jesmond Avenue, Jesmond', NULL, 'Newcastle upon Tyne', 'NE2 3JU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wooler Tennis Club', 'Weetwood Avenue', NULL, 'Wooler', 'NE71 6AG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wylam Lawn Tennis Club', 'Elm Bank Road', NULL, 'Wylam', 'NE41 8HT');

-- =============================================
-- ISLE OF MAN (5 clubs)
-- =============================================
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Albany Lawn Tennis Club', 'Ballaughton Meadows', NULL, 'Douglas', 'IM2 1JH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Castletown Lawn Tennis Club', 'Malew Street', NULL, 'Castletown', 'IM9 1AE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Douglas Lawn Tennis Club', 'Kensington Road', NULL, 'Douglas', 'IM1 3EL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Port Erin Lawn Tennis Club', 'Breagle Glen Tennis Court, St Georges Crescent', NULL, 'Port Erin', 'IM9 6HR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ramsey Tennis Club', 'Kerrowmoar, Jurby Road', NULL, 'Ramsey', 'IM8 3NZ');

-- =============================================
-- YORKSHIRE (153 clubs)
-- =============================================
INSERT INTO Clubs (Name, Town) VALUES ('Abbeydale TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ackworth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Adel TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Almscliffe TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Alne TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Alwoodley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Appleton Roebuck TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Austwick TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bardsey TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Barnsley LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Barwick-in-Elmet TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Batley Sports & Tennis Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Beauchief TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Beckfoot & Bingley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bedale TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Beeford TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Beverley & East Riding LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Beverley Town TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bishopthorpe TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Boroughbridge TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Boston Spa TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Boston Spa Academy Tennis Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bradfield TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Brentwood TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bridlington LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Brough TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Bubwith TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Chapel Allerton LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cherry Burton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cleckheaton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cliffe TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Collingham TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Copmanthorpe TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cottingham TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cragg Vale TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Craven TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Cross Hill TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Dacre TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Danby TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd Harrogate', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('David Lloyd York', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Denby Dale TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Doncaster LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Dore & Totley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Down The Line Tennis Academy', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Driffield LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Dunnington TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ecclesall LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Elland TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Escrick TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Fulford TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Fulwood LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Goole Tennis Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Graves TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Graves Health & Sports Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Great Ayton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Gregory Fields TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Grove LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Grove Hill Otley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Hackness & Scarborough TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Hallam Grange LTC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Hallamshire Tennis & Squash Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Harlow TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Harrogate Racquets Club Ltd', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Harrogate Spa Tennis Centre Ltd', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Harrogate Sports & Fitness Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Heaton Tennis & Squash Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Hessle TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Heworth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Holmfirth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Horsforth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Hovingham TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Huddersfield LT & Squash Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ilkley LT & Squash Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('JCCS South Leeds', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Kirkbymoorside TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Kirkstall Abbey TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Knaresborough King James TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Leeds Beckett University Tennis', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Linton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Liversage TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Longley Community Sports Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Malton Rackets Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Market Weighton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Marsden TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Mashamshire TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Mexborough TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Mirfield TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Northallerton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Northowram TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Nuffield Tennis Academy', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Park TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Pocklington TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Pool in Wharfedale TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Poppleton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Queens Sports Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Raskelf TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rastrick TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rawdon Golf Tennis & Padel Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Riddlesden TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Ripon Tennis Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rotherham Moorgate TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Roundhay TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rowntree Park TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rufforth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Rustlings TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Salts TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sandal TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Scalby TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Selby TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Shadwell TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sheffield Parks Tennis', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Shepley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sheriff Hutton TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Skipton Tennis Centre', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Slazenger Sports & Social Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sledmere TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('South Cave TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('South Yorkshire Visually Impaired TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sproatley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('St Andrews TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('St Chads TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('St Peters TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Stamford Bridge TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Starbeck TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Stocksbridge TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Stokesley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Sutton Upon Derwent TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Swanland TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Tadcaster TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Thirsk TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Thongsbridge TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Thorncliffe TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Thorner Victory Hall TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Todmorden TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Upper Armley TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wakefield TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wellholme TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wellholme Park TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('West Tanfield Memorial TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('West Yorkshire TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Westfields TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wetherby Castlegarth TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wetherby Padel Club', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wheatley Hills TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wheldrake TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Whitkirk TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Wiggington TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Withernsea TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('York TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('Yorebridge TC', 'Yorkshire');
INSERT INTO Clubs (Name, Town) VALUES ('York St John University Tennis Centre', 'Yorkshire');
