-- Part 1: Norfolk, Bedfordshire, Suffolk, Cambridgeshire

-- Norfolk (41 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Acle Tennis Club', 'Bridewell Lane', 'Acle', 'Norwich', 'NR13 3RA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Alive West Norfolk', 'Alive Lynn Sport, Greenpark Avenue', NULL, 'Kings Lynn', 'PE30 2NB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Aylsham Tennis Club', 'Sir Williams Lane', NULL, 'Aylsham', 'NR11 6AJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Blofield Tennis Club', 'Margaret Harker Hall, Yarmouth Road', NULL, 'Bloefield', 'NR13 4LE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Brooke & District Tennis Club', 'Norwich Road', NULL, 'Brooke', 'NR15 1AB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The Burnhams Tennis Club', 'Station Road', NULL, 'Burnham Market', 'PE31 8HA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cringleford Tennis Club', 'Oakfields Road', NULL, 'Cringleford', 'NR4 6XF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cromer Lawn Tennis & Squash Club', 'Norwich Road', NULL, 'Cromer', 'NR27 0EX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Norwich', 'Drayton High Road', 'Drayton Road', 'Norwich', 'NR6 5DU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Deepdale & Brancaster Staithe Tennis Club', 'Village Hall Playing Field, Main Road', NULL, 'Brancaster Staithe', 'PE31 8DD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Dersingham Tennis Club', NULL, NULL, 'Dersingham', 'PE31 6JB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Diss Heywood Tennis Club', 'Walcot Road', NULL, 'Diss', 'IP22 4DH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('East Anglia Tennis & Squash Club', 'Lime Tree Road', NULL, 'Norwich', 'NR2 2NQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Easton Tennis Centre', 'Easton College', NULL, 'Easton', 'NR9 5DX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eaton Park', 'South Park Avenue', NULL, 'Norwich', 'NR4 7AZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Fakenham Tennis Club', 'Fakenham Sports Centre, The Racecourse', 'Pudding Norton', 'Fakenham', 'NR21 7NY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gorleston Tennis Club', 'Orde Avenue', 'Gorleston', 'Great Yarmouth', 'NR31 6SZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Great Massingham Tennis & Multi-Sport Club', 'Village Hall, Station Road', NULL, 'Great Massingham', 'PE32 2HU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harford Park', 'Ipswich Road', NULL, 'Norwich', 'NR4 6LQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harleston Tennis & Squash Club', 'Memorial Leisure Centre, Wilderness Lane', NULL, 'Harleston', 'IP21 4RL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harling Sportspark', 'Recreation Ground, Church Road', NULL, 'East Harling', 'NR16 2NA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Heigham Park', 'The Avenues', NULL, 'Norwich', 'NR2 3HW');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hempnall Tennis Club', 'Hempnall Playing Field', NULL, 'Hempnall', 'NR15 2NG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hingham Tennis', 'Hingham Sports Hall, Watton Road', NULL, 'Hingham', 'NR9 4HB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hunstanton Recreation Ground', 'Cromer Road', NULL, 'Hunstanton', 'PE36 6BZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lakenham Recreational Ground', 'City Road', NULL, 'Norwich', 'NR1 2HL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Loddon Tennis Club', 'George Lane', NULL, 'Loddon', 'NR14 6NB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('North Elmham Tennis Club', 'The Recreation Ground, Holt Road', NULL, 'North Elmham', 'NR20 5JA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ormiston Venture Academy', 'Oriel Avenue', 'Gorleston', 'Great Yarmouth', 'NR31 7JJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Reepham Tennis Club', 'Stimpsons Piece, Bartle Court', NULL, 'Reepham', 'NR10 4LL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('South Creake Tennis Club', 'The Playing Field', NULL, 'South Creake', 'NR21 9PD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stanmore Tennis Club', 'Stanmore Road', 'Thorpe St Andrew', 'Norwich', 'NR7 0HB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Taverham Tennis Club', 'c/o The Village Hall, Sandy Lane', NULL, 'Taverham', 'NR8 6JR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Terrington St Clement Tennis Club', 'Terrington St Clement Memorial Field, Benns Lane', NULL, 'Terrington St Clement', 'PE34 4JY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Titan Tennis Academy', 'Kings Gardens, King Street', NULL, 'Thetford', 'IP24 2AP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('UEA Sportspark', 'Sportspark, University Drive', NULL, 'Norwich', 'NR4 7TJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Waterloo Park', 'Angel Road', NULL, 'Norwich', 'NR3 3HU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wells Town Tennis Club', 'Gales Road', NULL, 'Wells-next-the-Sea', 'NR23 1DL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('West Norfolk Lawn Tennis Club', 'The Cricket Ground', 'North Runcton', 'Kings Lynn', 'PE33 0RA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wymondham Tennis Club', 'Kett''s Park, Harts Farm Road', NULL, 'Wymondham', 'NR18 0WP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Tennis for Life', NULL, NULL, 'Norwich', NULL);

-- Bedfordshire (22 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ampthill Great Park Tennis Club', 'Woburn Road', NULL, 'Bedford', 'MK45 2HX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bedford Lawn Tennis Club', 'Bedford Sports and Hockey Centre, Chester Road', NULL, 'Bedford', 'MK40 4HL');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Biddenham Tennis Club', 'Deep Spinney', 'Biddenham', 'Bedford', 'MK40 4PZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Biggleswade Conservative Tennis Club', 'St Andrews Street', NULL, 'Biggleswade', 'SG18 8BA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Dunstable Tennis Club', 'Playing Fields, Downs Road', NULL, 'Dunstable', 'LU5 4DD');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eaton Bray Lawn Tennis Club', 'School Lane', NULL, 'Dunstable', 'LU6 2DT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Eversholt Tennis Club', 'Church End', NULL, 'Milton Keynes', 'MK17 9DU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Flitwick & Ampthill LTC', 'Astwood Drive, Off Windmill Road', 'Flitwick', 'Bedford', 'MK45 1EN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Harrold Lawn Tennis Club', 'Harrold Centre, High Street', NULL, 'Bedford', 'MK43 7BH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Langford Tennis Club', 'King George''s Playing Field', NULL, 'Biggleswade', 'SG18 9QY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Leighton Buzzard Tennis Club', 'Bell Close', NULL, 'Leighton Buzzard', 'LU7 1RX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Linslade Tennis Club', 'Memorial Playing Fields, Mentmore Road', NULL, 'Leighton Buzzard', 'LU7 2NY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Pavenham Tennis Club', 'The Playing Fields, Pavenham Village Hall', NULL, 'Bedford', 'MK43 7PH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Potton Tennis Club', 'Mill Lane Pavilion, Mill Lane', NULL, 'Sandy', 'SG19 2PG');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Riverside Tennis Club', 'Goldington Road', NULL, 'Bedford', 'MK40 3EA');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sharnbrook Lawn Tennis Club', 'Lodge Road', 'Sharnbrook', 'Bedford', 'MK44 1JP');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Slip End Tennis Club', 'Playing Field Church Road', 'Slip End', 'Luton', 'LU1 4BJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Studham Tennis & Pickleball Club', 'Clements End Road', NULL, 'Dunstable', 'LU6 2NQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Toddington Tennis Club', 'The Recreation Ground, Luton Road', 'Toddington', 'Dunstable', 'LU5 6DE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Venue 360 Tennis', 'Venue 360, 20 Gipsy Lane', NULL, 'Luton', 'LU1 3JH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Westoning Tennis Club', 'Greenfield Road', NULL, 'Bedford', 'MK45 5JB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woburn Sands Tennis Club', '9 Club Lane', 'Woburn Sands', 'Milton Keynes', 'MK17 8FA');

-- Suffolk (43 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Adastral Park Tennis Club', 'Adastral Park, Martlesham Heath', NULL, 'Ipswich', 'IP5 3RE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Beccles Tennis Club', 'Alan Hutchinson Way, Off Common Lane', NULL, 'Beccles', 'NR34 9RH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bramford Tennis Club', 'The Playing Fields, Acton Road', NULL, 'Bramford', 'IP8 4HU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bungay Tennis Club', 'Maltings Meadow Sports Club, Pirnhow Street', 'Ditchingham', 'Bungay', 'NR35 2RU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Christchurch Park Tennis', 'Christchurch Park', NULL, 'Ipswich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Copdock And Washbrook Tennis & Badminton Club', NULL, NULL, 'Copdock', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Ipswich', NULL, NULL, 'Ipswich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('East Bergholt Tennis Club', NULL, NULL, 'East Bergholt', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Exning Tennis Club', NULL, NULL, 'Exning', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Felixstowe Lawn Tennis Club', 'Bath Road', NULL, 'Felixstowe', 'IP11 7JN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Framlingham College Tennis', NULL, NULL, 'Framlingham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Framlingham Lawn Tennis Club', 'Badingham Road', NULL, 'Woodbridge', 'IP13 9HS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Fressingfield Tennis Club', NULL, NULL, 'Fressingfield', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Grundisburgh Tennis Club', 'Grundisburgh Playing Fields, Ipswich Road', NULL, 'Grundisburgh', 'IP13 6TJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hadleigh Tennis Club', NULL, NULL, 'Hadleigh', 'IP7 5NE');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Halesworth Tennis Club', NULL, NULL, 'Halesworth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Haverhill Tennis Club', 'Ehringshausen Way', NULL, 'Haverhill', 'CB9 0BB');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Holbrook Tennis Club', NULL, NULL, 'Holbrook', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ipswich Sports Club', 'Henley Road', NULL, 'Ipswich', 'IP1 4NJ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Kesgrave Tennis Club', NULL, NULL, 'Kesgrave', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lavenham Lawn Tennis Club', NULL, NULL, 'Lavenham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Lowestoft Town Tennis and Pickleball Club', 'Denes Oval', NULL, 'Lowestoft', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Newmarket Tennis Club', NULL, NULL, 'Newmarket', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Newmarket URC Tennis Club', NULL, NULL, 'Newmarket', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Risbygate Sports Club', NULL, NULL, 'Bury St Edmunds', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Roundwood Lawn Tennis Club', 'Salmet Close', NULL, 'Ipswich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Saxmundham Tennis Club', NULL, NULL, 'Saxmundham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Somersham & District Community Association', NULL, NULL, 'Somersham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Southwold & District Tennis Club', NULL, NULL, 'Southwold', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sproughton Tennis Club', NULL, NULL, 'Sproughton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('St Johns Tennis Club', 'Westbury Road', NULL, 'Ipswich', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stoke By Clare Tennis Club', NULL, NULL, 'Stoke by Clare', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stowmarket Lawn Tennis Club', 'Lake Side', NULL, 'Stowmarket', 'IP14 1SX');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stradbroke Tennis Club', NULL, NULL, 'Stradbroke', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Sudbury Tennis Club', NULL, NULL, 'Sudbury', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Thurlow Tennis Club', NULL, NULL, 'Thurlow', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ufford Tennis Club', NULL, NULL, 'Ufford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Victory Ground Tennis Players', NULL, NULL, 'Suffolk', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wickham Market Tennis Club', NULL, NULL, 'Wickham Market', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woodbridge Tennis Club', NULL, NULL, 'Woodbridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Woolpit Tennis Club', NULL, NULL, 'Woolpit', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wortham Tennis Club', NULL, NULL, 'Wortham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('YM Tennis Ipswich', NULL, NULL, 'Ipswich', NULL);

-- Cambridgeshire (52 clubs)
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cambridge Tennis Academy', 'Chesterton Sports Centre, Gilbert Road', NULL, 'Cambridge', 'CB4 3NY');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cocks and Hens Tennis Club', 'Grantchester Road', NULL, 'Cambridge', 'CB3 9ED');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Foxton Village Tennis Club', 'Recreation Ground, Off St. Laurence Road', NULL, 'Foxton', 'CB22 6SF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Fulbourn Tennis Club', 'Recreation Ground, Home End', NULL, 'Fulbourn', 'CB21 5BS');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Girton Tennis Club', 'Cambridge Road', NULL, 'Girton', 'CB3 0FH');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Great Shelford Tennis Club', 'Woollards Lane', NULL, 'Great Shelford', 'CB22 5LZ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Haslingfield Lawn Tennis Club', 'New Road', NULL, 'Haslingfield', 'CB23 1LR');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hauxton Tennis Club', 'Hauxton Sports Ground, Cambridge Road', NULL, 'Hauxton', 'CB22 5HT');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Histon Tennis Club', 'Recreation Ground, New Road', NULL, 'Impington', 'CB24 9LU');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Longstanton Tennis Club', 'Sports & Social Club, Recreation Ground', NULL, 'Longstanton', 'CB24 3DN');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Stapleford Tennis Club', 'Recreation Ground, Gog Magog Way', NULL, 'Stapleford', 'CB22 5BQ');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hills Road Sports & Tennis Centre', 'Purbeck Road', NULL, 'Cambridge', 'CB2 8PF');
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Barton Tennis Club', NULL, NULL, 'Barton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Bourn Sports Club', NULL, NULL, 'Bourn', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Buckden Tennis Club', NULL, NULL, 'Buckden', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cambourne Lawn Tennis Club', NULL, NULL, 'Cambourne', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cambridge Lawn Tennis Club', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Castor and Ailsworth Tennis Club', NULL, NULL, 'Castor', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('10is Academy Ely', NULL, NULL, 'Ely', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chatteris St Peters Tennis Club', NULL, NULL, 'Chatteris', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Chippenham Tennis Club', NULL, NULL, 'Chippenham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Cottenham Tennis Club', NULL, NULL, 'Cottenham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('D''Abo Tennis Club', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Cambridge', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('David Lloyd Club Peterborough', NULL, NULL, 'Peterborough', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Duxford Lawn Tennis Club', NULL, NULL, 'Duxford', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ely Tennis Club', NULL, NULL, 'Ely', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Fen Drayton Tennis Club', NULL, NULL, 'Fen Drayton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Gransdens Lawn Tennis Club', NULL, NULL, 'Great Gransden', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Helpston Lawn Tennis Club', NULL, NULL, 'Helpston', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Hemingfords Lawn Tennis Club', NULL, NULL, 'Hemingford Grey', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Houghton & Wyton Tennis Club', NULL, NULL, 'Houghton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Huntingdon Tennis Club', NULL, NULL, 'Huntingdon', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Longthorpe Lawn Tennis Club', NULL, NULL, 'Longthorpe', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Meldreth Tennis Club', NULL, NULL, 'Meldreth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Milton Tennis Club', NULL, NULL, 'Milton', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Needingworth Tennis Club', NULL, NULL, 'Needingworth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Oakington & Westwick Tennis Club', NULL, NULL, 'Oakington', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Orwell Tennis Club', NULL, NULL, 'Orwell', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Papworth Tennis Club', NULL, NULL, 'Papworth', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Park Tennis Cambridge', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Phennards Lawn Tennis Club', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Ramsey Tennis Club', NULL, NULL, 'Ramsey', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Soham Tennis Club', NULL, NULL, 'Soham', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('St Neots Lawn Tennis Club', NULL, NULL, 'St Neots', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Steeple Morden Tennis Club', NULL, NULL, 'Steeple Morden', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Swavesey and Over Tennis Club', NULL, NULL, 'Swavesey', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('The City of Peterborough Tennis Club', NULL, NULL, 'Peterborough', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Mikes Tennis Academy Club', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('West Hill Park Tennis Club', NULL, NULL, 'Cambridge', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Wisbech Lawn Tennis Club', NULL, NULL, 'Wisbech', NULL);
INSERT INTO Clubs (Name, AddressLine1, AddressLine2, Town, Postcode) VALUES ('Love Tennis Academy', NULL, NULL, 'Cambridge', NULL);
